### ISSUE TITLE
Migration: Rename column fails on Linux

### ISSUE THREAD

**Issue by Jan-Olof** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1016]
### Steps to reproduce
After upgrading to version 3 the migration script produced this code:

```sql
ALTER TABLE `ProcedureStates` RENAME COLUMN `ActiveOperation_UnitProcedureUnitId` TO `ProcedureEntityId`;
```
### The issue
The Rename column syntax above fails on Ubuntu, but works on Windows.

### Further technical details

MySQL version: 8
Operating system: Ubuntu
Pomelo.EntityFrameworkCore.MySql version: 3.1.1
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:

**Comment by lauxjpn** [comment]
Please post the *exact* MySQL version, so we can try to reproduce the issue.

**Comment by Jan-Olof** [comment]
5.7.29-0ubuntu0.18.04.1

Windows: ver. 8.0.18.

**Comment by lauxjpn** [comment]
`RENAME COLUMN` is only supported when using MySQL 8.0.0+.
If you do not explicitly specify the server version, the newest one is assumed. If you specify a version below MySQL 8.0.0, `CHANGE COLUMN` instead of `RENAME COLUMN` is used.

Take a look at our [front page](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#3-services-configuration) here on GitHub, for an example how to set the `ServerVersion`.

**Comment by Jan-Olof** [comment]
Ok, thanks! Sorry for wasting your time. I really thought that we had version 8 on both and was surprised to see ver 5 on Ubuntu. My mistake.
