### ISSUE TITLE
Renaming Entity

### ISSUE THREAD

**Issue by cetubig** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1030]
Renaming entity will drop and create the table instead of renaming it only.

**Comment by crozone** [comment]
This is an inherent limitation of EF, not Pomelo directly. EF cannot normally distinguish between a table drop/create, and a rename.

The trick to tell it that it's a rename is to set the table name manually, either via an attribute on the entity class, or via the OnModelCreating fluent API.

The sequence goes like:

1. Using the **original** entity name, set the table name to the new value. Try to make sure this new name is correct for the new entity, or you may end up with an additional migration.

E.g `builder.Entity<OriginalEntity>().ToTable("RenamedEntity");`

2. Generate a migration. This will create the correct rename table migration for the entity.
Verify this migration is correct. If you are using Pomelo 2.2.6, check for `migrationBuilder.DropPrimaryKey` and `AddPrimaryKey` entries and delete them, since these are not necessary for MySQL and will cause issues with generating idempotent SQL scripts. This is fixed in 3.1.

3. Rename the actual entity class.

4. Generate another migration to update the model snapshot with the new entity names.

If you then want to remove the `.ToTable("RenamedEntity");` to fall back to convention based table naming:

5. Remove the `.ToTable("RenamedEntity");`. If you got the table name correct, the convention based name should be the same as the current name.

6. Generate a final migration to verify that the table isn't renamed again. If it was, revert all steps, correct the name, and redo. If the migration was empty, you can revert it.

For more information, see this stack overflow question:

https://stackoverflow.com/questions/13296996/entity-framework-migrations-renaming-tables-and-columns

**Comment by lauxjpn** [comment]
Basically, there are heuristics implemented, that can detect a table rename in _some_ cases.

But renaming is one of those operations, where you definitely want to check the generated migration code afterwards and change the `DropTable` and `CreateTable` calls to `RenameTable` where necessary.

**Comment by cetubig** [comment]
EF Core has rename table just like these.

            migrationBuilder.DropPrimaryKey(
                name: "PK_LogFieldsConfiguration",
                table: "LogFieldsConfiguration");

            migrationBuilder.RenameTable(
                name: "LogFieldsConfiguration",
                newName: "LogFieldsConfigurations");

            migrationBuilder.AddPrimaryKey(
                name: "PK_LogFieldsConfigurations",
                table: "LogFieldsConfigurations",
                column: "Id");
