### ISSUE TITLE
不要瞎改BUG  ToTraceString  和 tosql 解决一下，不然这个东西完全废了

### ISSUE THREAD

**Issue by handashuai** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1038]
BUG  ToTraceString  和 tosql 解决一下

能不能  微软的官方   移植过来 不要瞎改

**Comment by lauxjpn** [comment]
There is no `ToTraceString()` implementation in EF Core and it should not be needed, because EF Core does log database queries using the .NET Core logging infrastructure (see [Logging](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging).

For EF Core 3.x.x there is no official `ToSql()` support yet, but it has already been made part of EF Core 5 by Microsoft as `ToQueryString()` (see #999).

There are multiple older issues about this method and some contain code that can be used as an extension methods for EF Core below 5.x:
* [Create ToSql extension method](https://github.com/dotnet/efcore/issues/9414)
* [Provide a simple way to get SQL statements generated from EF queries](https://github.com/dotnet/efcore/issues/6482)
* [Create ToSql extension method](https://github.com/dotnet/efcore/issues/9414)

**Comment by handashuai** [comment]
？？？？？i   need   it

**Comment by mguinness** [comment]
As already stated there is no `ToTraceString()` implementation in EF Core, see [Get SQL code from an Entity Framework Core IQueryable<T>](https://stackoverflow.com/questions/37527783/get-sql-code-from-an-entity-framework-core-iqueryablet).
