### ISSUE TITLE
MySqlConnector Version used

### ISSUE THREAD

**Issue by ronnypmuliawan** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1153]
Hi all,

Writing this issue to query about the plan for the MySqlConnector version used. Is there any plan to bump the version used to 1.0.0 and above?

**Comment by lauxjpn** [comment]
We will use MySqlConnector version 1.0.0+ in Pomelo 5.0.0. See PR #1108 
The reason is, that MySqlConnector 1.0.0 changed its namespace. Since we strive to comply as much as possible with [SemVer 2](https://semver.org/spec/v2.0.0.html) and changing a namespace is a breaking change, we should implement this only in a major version upgrade.

**Comment by ronnypmuliawan** [comment]
Noted on that. Is there any timeline for Pomelo 5.0.0? Is it planned to be released in tandem with EF Core 5.0?

**Comment by mguinness** [comment]
Updates on 5.0 will be posted at [EF Core 5 Preview support](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088), current work is on JSON support.

**Comment by ronnypmuliawan** [comment]
Thanks for the info, will follow the progress on the 5.0 updates.
