### ISSUE TITLE
A feature like this? 

### ISSUE THREAD

**Issue by Flithor** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1219]
https://github.com/dotnet/efcore/issues/19113
looks I can't generate commented class files by use Scaffold-DbContext with "Pomelo.EntityFrameworkCore.MySql"

Pomelo.EntityFrameworkCore.MySql Version I used: 3.2.3

**Comment by lauxjpn** [comment]
@Flithor This feature has been added to the EF Core 6.0 branch.
Do you mean you cannot generate them with the latest bits for EF Core 6.0 and the Pomelo 5.0 alpha prerelease?

**Comment by Flithor** [comment]
uh I use 3.2.3(the last release version now)

**Comment by lauxjpn** [comment]
@Flithor In that case, since this feature has been implemented for EF Core 6.0, you will need to use that version in conjunction with Pomelo.

At this time, Pomelo does not yet have a EF Core 6.0 supporting release, so you will need to wait for that.
Since this feature is provided by EF Core itself, there is nothing for us to do here.

**Comment by ErikEJ** [comment]
This is available in EF Core Power Tools today.
