### ISSUE TITLE
Do we have a plan to support Database Backup?

### ISSUE THREAD

**Issue by JeffreySu** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1226]
### The issue
There are some projects support for Database Backup at runtime without the console, like: https://github.com/MySqlBackupNET.

But if I want to use the Backup function, I have to choose between MySql.Data and Pomelo.EntityFrameworkCore.MySql, otherwise the project will throw an exception:

```
Eoor	CS0433	Type “MySqlConnection” exists both in “MySql.Data, Version=8.0.21.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d” and“MySqlConnector, Version=0.61.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92”中	Senparc.Ncf.Database.MySql.Backcup	E:\xxx\MySqlWithBackupDatabaseConfiguration.cs	28
```

Because MySqlBackupNET just supports for MySql.Data, which have same class names with  Pomelo.EntityFrameworkCore.MySql such as `MySqlConnection` ,`MySqlCommand`(may be in Pomelo.EntityFrameworkCore.MySql they have the same class name and same namespace?), so the projects cannot reference MySqlBackupNET(MySql.Data) and Pomelo.EntityFrameworkCore.MySql at the same time.

Do you have any plan to support the Backup function or push to MySqlBackupNET(or others) ?

**Comment by lauxjpn** [comment]
Since our 5.0 release uses `MySqlConnector` 1.0.x and the namespace in all versions since 1.0.0 has been changed from `MySql.Data` to `MySqlConnector`, this should not be an issue for future releases.

For releases prior to 5.0, take a look at the references from https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1006#issuecomment-574480200. They describe the general approach for using two packages with different implementations of the same type in the same namespace.
