### ISSUE TITLE
XML documentation is not included in the package

### ISSUE THREAD

**Issue by hainguyenthanh** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1258]
### Steps to reproduce
Add a reference to the package to a project in an IDE that supports viewing XML documentation, for example, Visual Studio. Use any types of methods provided by the package.

### The issue
No XML documentation is available when using this package. This issue costs developers a lot of time trying to figure out how to use the package's public APIs.

Please include the XML documentation files together with the assemblies in the package.

**Comment by lauxjpn** [comment]
@hainguyenthanh Looks fine when I try it:

### Visual Studio 2019, 16.8.2
![image](https://user-images.githubusercontent.com/14178357/100191983-6451a380-2ef1-11eb-8182-ba2990bbf16a.png)

### Rider 2020.3 EAP 8
![image](https://user-images.githubusercontent.com/14178357/100192498-623c1480-2ef2-11eb-84d9-802e330bd2c6.png)

Also, the package itself _does_ contain the necessary XML docs file:

![image](https://user-images.githubusercontent.com/14178357/100192078-8e0aca80-2ef1-11eb-997e-696dabe37cd0.png)

So to find out where the issue is, we have to investigate a bit further:
* For what method do you expect there to be XML documentation available?
* What IDE are you using?

It might also be helpful, if you can share your project/solution with us.

**Comment by hainguyenthanh** [comment]
@lauxjpn I'm using the stable version 3.2.4 and it seems that the XML documentation is not included in this version. The 5.0.0 alpha 2 version does include documentation.

**Comment by lauxjpn** [comment]
@hainguyenthanh Ah, that is correct, we included the XML docs in the major 5.0 upgrade.
I'll add the docs to the 3.2-maint branch as well.
