### ISSUE TITLE
Simplify DI API

### ISSUE THREAD

**Issue by yukozh** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1262]
It is so complex now. We should create a simple `.UseMySql(string)` as before. And use latest mysql version as default. Use the following mysql options as default mysql options. It's not a good user experience for usage with following API.
```
            services.AddDbContextPool<YourDbContext>(
                dbContextOptions => dbContextOptions
                    .UseMySql(
                        // Replace with your connection string.
                        "server=localhost;user=root;password=1234;database=ef",
                        // Replace with your server version and type.
                        // For common usages, see pull request #1233.
                        new MySqlServerVersion(new Version(8, 0, 21)), // use MariaDbServerVersion for MariaDB
                        mySqlOptions => mySqlOptions
                            .CharSetBehavior(CharSetBehavior.NeverAppend))
                    // Everything from this point on is optional but helps with debugging.
                    .EnableSensitiveDataLogging()
                    .EnableDetailedErrors();
            ));
```

Expected:

```
 services.AddDbContextPool<YourDbContext>(x => x.UseMySql("Server=localhost;user=root;pwd=123456;database=newdb"));
```

**Comment by lauxjpn** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088#issuecomment-726091533 and the following comments for that.

So it is intentional, that users need to make a conscious choice how they want to handle server versions.
The only difference to before is, that there is one more mandatory parameter, so that should not be overly complicated.

We will simplify the `ServerVersion` API a bit however, meaning that you can also instantiate MySQL and MariaDB server versions using the base class:

```c#
ServerVersion.Create(new Version(8, 0, 21), ServerType.MySql)
ServerVersion.Create("8.0.21-mysql") // formerly ServerVersion.FromString()
```

That means that users will find the common options on the `ServerVersion` base class, which will help discoverability.

**Comment by mguinness** [comment]
My 2¢, I would add an additional extension method UseMariaDb in addition to UseMySql and default to AutoDetect() if no version parameter is provided.  I don't have a strong feeling either way, but I agree that using latest version would be counter productive.

**Comment by lauxjpn** [comment]
@mguinness I think the `UseMariaDb()` extension method would generally not be a bad idea, but users would still need the option to specify a server version and type dynamically. The question would then be, how this general method would be called, if `UseMySql()` would already be exclusively used for Oracle's MySQL implementation (which would be the logical consequence if `UseMariaDb()` is used exclusively for MariaDB). Maybe something like `UseMySqlCompatible()`?

The other issue with `UseMySql()` being exclusive to Oracle's MySQL implementation is, that everybody is using the method currently for all server implementations, including MariaDB. So unless we make it obsolete and use another method for Oracle's implementation, MariaDB users would continue to use it. But using another method name than `UseMySql()` for actual MySQL implementations might be awkward. So I don't currently see, how to solve this one.

Regarding auto detection as the default, this would in all cases open a connection to the database server when the `UseX()` method is being called, which is an additional server roundtrip that might not be needed at all and would happen way before what is usually the case for EF Core providers. And technically, if auto detection is being used, then using a server specific `UseX()` method is also not really needed, because the auto detection includes the server type anyway.

So while auto detection is definitely much better then just assuming the latest version, it still comes with some tradeoffs. If we make it the default, then 99% of the users will use it and don't think about the consequences down the road (not just the additional roundtrip, but also e.g. developing on a newer version of MySQL on the development machine, but deploying to a MySQL version on the production server that is just a couple of minor versions older, which then could break the app because of some expressions being translated to statements that are not supported by the server implementation).

There are also some additional benefits to the current implementation. I have a commit prepared that lets you specify multiple server versions (you can basically merge multiple `ServerVersion` derived classes into one and then use the merged one). So you can basically say, that you app needs to run on MySQL 8.0.21, but also on MariaDB 10.4.8, so only features that are available in both server implementations will be assumed by us.
