### ISSUE TITLE
Set Connection variables

### ISSUE THREAD

**Issue by msmolka** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#133]
Hello
I have a question, can you point me to documentation of usage this library. I would like to know how to set MySql specific connection variables e.g. How to set (and where is the best place) collation_connection

Kind Regards

**Comment by Kagamine** [comment]
@bgrainger, could you anwser his question?

**Comment by bgrainger** [comment]
Pomelo.EntityFrameworkCore.MySql uses [MySqlConnector](https://github.com/mysql-net/MySqlConnector) as its underlying MySQL connection library.

MySqlConnector supports [these connection string options](https://mysql-net.github.io/MySqlConnector/connection-options/). We do not currently support setting `CharSet`, if that's the [Connector/Net option](https://dev.mysql.com/doc/connector-net/en/connector-net-connection-options.html) you're referring to when you say "collation_connection".

MySqlConnector will always use UTF-8 (i.e., `utf8_mb4`) when connecting to MySQL Server (because .NET itself is Unicode-based and doesn't use national character sets).

You could execute a `SET CHARACTER SET` command to change this, but I would strongly recommend against this because MySqlConnector will expect its results to be in UTF-8 and won't know how to translate them from a different character set.

Can you explain your use case for changing `collation_connection` so I can understand if and why it might need to be supported?

**Comment by bgrainger** [comment]
(As for changing connection string options in general, not just the specific `collation_connection` setting, I don't know if/how Pomelo.EntityFrameworkCore.MySql exposes those to its caller; @Kagamine can you answer that part?)

**Comment by msmolka** [comment]
Thank you for the answer. I wasn't sure what is default collation when doing connection through driver. But in fact I was wondering how to set MySql default variables.

**Comment by Kagamine** [comment]
EF Core does not support specific collation.

**Comment by msmolka** [comment]
Thank you

**Comment by caleblloyd** [comment]
> As for changing connection string options in general, not just the specific `collation_connection` setting, I don't know if/how Pomelo.EntityFrameworkCore.MySql exposes those to its caller

@bgrainger Pomelo.EntityFrameworkCore.MySql receives a MySqlConnector Connection String through a DbContext ([example](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/AppDb.cs#L57)).

We [set a couple defaults](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/3b600717db2710eec0c3da3c316d5e8c3971fe13/src/Pomelo.EntityFrameworkCore.MySql/Extensions/MySqlDbContextOptionsExtensions.cs#L25-L29), specifically `AllowUserVariables = true` and `UseAffectedRows = false` (the latter coming from discussion in #93)

The resulting connection string after defaults are set gets sent to MySqlConnector in the library code
