### ISSUE TITLE
CharSet should be ignored when ColumnType is JSON

### ISSUE THREAD

**Issue by hez2010** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1365]
### Steps to reproduce
```csharp
class Model
{
        [Column("property1", TypeName = "json")]
        public string Property1 { get; set; }
}

await dbContext.Database.EnsureCreatedAsync();
```

### The issue
CharSet should be ignored when ColumnType is JSON, otherwise it will be an invalid statement.

```
Exception message:
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `Model` (
          property1 json CHARACTER SET utf8 NULL;
      );
Failed executing DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
MySqlConnector.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CHARACTER SET utf8 NULL' at line 2
```

### Further technical details

MySQL version: 5.7 and 8.0
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha.2
Microsoft.AspNetCore.App version: 5.0.4

**Comment by mguinness** [comment]
The [JSON Data Type](https://mariadb.com/kb/en/json-data-type/) is an alias for `LONGTEXT` in MariaDB, but I would assume that it's implicitly defined as `utf8mb4` with a `json_valid()` constraint check.

The logic for field generation is in MySqlMigrationsSqlGenerator class and it should be a simple change, so if someone would like to create a PR it would be welcomed.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/ce1f7feac25bfa7cf6c96948fc5e644113378dab/src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs#L1147-L1182

**Comment by lauxjpn** [comment]
@xfoxfu Do you have a `HasCharSet()` in your Fluent API model definition (which would be applied in the [MySqlMigrationsSqlGenerator.GetColumnTypeWithCharSetAndCollation()](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/91addbf96668b211dea040b070696d15b6a92997/src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs#L1189) method), or is this just the legacy `CHARACTER SET` statement, that gets appended to all `string` columns, unless you specify `CharSetBehavior(CharSetBehavior.NeverAppend)` when you setup your context (which would be applied in [MySqlTypeMappingSource.FindRawMapping()](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/eb7c2cda242953007c3da639ef81ba72271fdd93/src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs#L387))?

Because if it is the latter, than you should just set `CharSetBehavior(CharSetBehavior.NeverAppend)` for the time being (see our [sample code](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#3-services-configuration) on our home page), because the whole mechanism will be gone with the next prerelease anyway (in favor of `HasCharSet()` calls in the model definition).

If it is the former, then I am not convinced that we should do something about it, because as @mguinness already pointed out:

> The [JSON Data Type](https://mariadb.com/kb/en/json-data-type/) is an alias for LONGTEXT in MariaDB [...]

Which means, that it should be legal to change its charset in MariaDB.

**Comment by xfoxfu** [comment]
It is the former case. I think it would be better if we simply ignore the `.HasCharSet` when generating SQL, or throw an exception.

**Comment by lauxjpn** [comment]
> I think it would be better if we simply ignore the `.HasCharSet` when generating SQL, or throw an exception.

I think it is okay to ignore it for MySQL, as it is indeed illegal there to change the charset for a JSON column. However, we should leave other database server implementations like MariaDB untouched (if it is legal to do, we should not artificially make it illegal in Pomelo, unless there is a very good reason for it).

This also needs to be done for the scaffolder then, so that if a JSON column is scaffolded, we don't generate `HasCharSet()` and `HasCollation()` (or `UseCollation()`) calls for the model definition.

**Comment by lauxjpn** [comment]
Actually, it turns out that MariaDB seems to force a charset of `utf8mb4` and a collation of `utf8mb4_bin` as well, when using the `json` type (alias for `longtext`), but doesn't if just `longtext` is used.
So there doesn't need to be a distinction between MySQL and MariaDB here, as both will implicitly use the charset of `utf8mb4` and the `utf8mb4_bin` collation.

However, since `json` is just an alias for `longtext` for MariaDB, it returns the type `longtext` from `information_schema.columns` when we scaffold it. Because Pomelo will only automatically enable the JSON support for properties with the column type `json`, users would currently need to manually change the as `longtext` scaffolded columns to `json`.

However, since `10.4.3`, MariaDB will automatically add a `JSON_VALID()` check constraint to `json` columns (see [JSON Data Type](https://mariadb.com/kb/en/json-data-type/) and [MDEV-13916: Enforce check constraint on JSON type](https://jira.mariadb.org/browse/MDEV-13916)), so we can use that to identify a `longtext` column with a charset of `utf8mb4` and a collation of `utf8mb4_bin` as `json`.
