### ISSUE TITLE
In some case ef core return empty collection from db

### ISSUE THREAD

**Issue by denisenko93** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1415]
### Steps to reproduce

Create project and configure to use mysql

```
options.UseMySql(
                BuildConnection().ConnectionString,
                new MySqlServerVersion(new Version(5, 7)));
```

Fetch data from database and get empty result

### The issue
Our application use ef core and pomelo in many cases. After upgrade version from .net core 3.1 to .net 5 in production environment the problem described below began to reproduce in only one place.
The problem could not be reproduced on the test environment.
After the problem occurred, restarting the site in IIS helped.

After rolling back the Pomelo version to 3.2.4 and ef core to 3.1.12, the problem can not reproduced. .net version remains the same.

### Further technical details

MySQL version: 5.7.26
Operating system: Windows server 2016 Standard (1607) Build: 14393.2273
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha.2
Microsoft.AspNetCore.App version: 5.0.3

Other details about my project setup:
IIS version: 10.0.14393.0

**Comment by denisenko93** [comment]
LINQ query is very simple:
```
ProductDeliveryCostInfo[] productDeliveryInfos = await ProductRepository
                .Queryable()
                .Where(x => productIds.Contains(x.Id))
                .Select(x => new ProductDeliveryCostInfo {Id = x.Id, UsdCurrency = x.UsdCurrency, FreeDelivery = x.FreeDelivery, WeightReal = x.WeightReal})
                .ToArrayAsync();
```
There are a lot of similar requests for the code base.
There is only an error in the logs that the object with the required Id was not found in the array.
The only difference with this method is that it is called a little more often than the others. (3-4) times per second.
The configuration and database are exactly correct, because the problem is solved either by manually restarting the site in iis or automatically

**Comment by lauxjpn** [comment]
@denisenko93 So a couple of thing:

* If you use MySQL 5.7.26, your `MySqlServerVersion` should also use `5, 7, 26` instead of only `5, 7`.
* Please try again with the official release of Pomelo `5.0.0`.
* Log the SQL queries through ASP.NET Core's logging mechanism (use `"Microsoft.EntityFrameworkCore": "Information"` as a `LogLevel` in your `appsettings.json`).
* Enable [sensitive data](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/extensions-logging?tabs=v3#sensitive-data) logging and [detailed query exceptions](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/extensions-logging?tabs=v3#sensitive-data).
* Explicitly add a message to your log, when the unexpected result returns to you, so it is clear when looking at the log, what the actual SQL query was at the time.

Then copy the SQL query that lead to the empty result (and related anything related) from the log and paste it in here.

**Comment by lauxjpn** [comment]
@denisenko93 Do you still need help with this issue?

**Comment by denisenko93** [comment]
Since the problem does not appear in a test environment, we need to choose a time frame to perform the recommended actions in a production environment. I will publish the results here

**Comment by lauxjpn** [comment]
@denisenko93 We haven't heard back from you. What is the status of this issue?

**Comment by lauxjpn** [comment]
@denisenko93 Since we haven't heard back from you, we are closing this issue for now.

**Comment by denisenko93** [comment]
After updating Pomelo to version 5.0.1, the problem can not reproduce

**Comment by lauxjpn** [comment]
@denisenko93 Thanks for letting us know!
