### ISSUE TITLE
EF Migration constantly removing "CHARACTER SET utf8mb4" from all text types

### ISSUE THREAD

**Issue by B-DAP** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1437]
### Steps to reproduce
Have a database with columns of types 
`varchar(100) CHARACTER SET utf8mb4`
`longtext CHARACTER SET utf8mb4` and similar

Upgrade to .NET 5 and Pomelo 5

### The issue
Any new migration that is created, removes `CHARACTER SET utf8mb4`
Example: 
`longtext CHARACTER SET utf8mb4` becomes `longtext`
`varchar(100) CHARACTER SET utf8mb4` becomes `varchar(100)`

Migration code snippet:

```
migrationBuilder.AlterColumn<string>(
                name: "VoucherUrl",
                table: "Viator_Order",
                type: "longtext",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "longtext CHARACTER SET utf8mb4",
                oldNullable: true)
                .Annotation("MySql:CharSet", "utf8mb4")
                .OldAnnotation("MySql:CharSet", "utf8mb4");
```

This is affecting all tables in the database. 
I can't figure out why this is happening, and how to stop it. 
### Further technical details

MySQL version: 5.6
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 5.0.0
Microsoft.AspNetCore.App version: 5.0.5

Other details about my project setup:

I have tried adding `modelBuilder.HasCharSet("utf8mb4");` and it made no difference.

**Comment by lauxjpn** [comment]
Using `longtext CHARACTER SET utf8mb4` as the store type name is obsolete. The store type should just be `longtext`.

The `AlterColumn()` operation in your example does the following:
* It replaces `longtext CHARACTER SET utf8mb4` with `longtext`.
* It keeps the `MySql:CharSet` annotation as `utf8mb4`.

The result should be the exact same column in the database, that you had before: a `longtext` with `utf8mb4` as the character set.

The operations get generated in this case, because you were not using `options.CharSetBehavior(CharSetBehavior.NeverAppend)` in your `UseMySql()` call in the past (`CharSetBehavior()` was removed entirely with #1244 for 5.0.0).

Since theses operations don't do anything (they generate `ALTER` statements, but they don't change anything), you can either just run them, or even simpler: just clear the `Up()` and `Down()` methods of their content and make this an empty migration (assuming you did not change anything else).

**Comment by B-DAP** [comment]
Thanks for the detailed explanation. Our database's default charset is set to just `utf8`, and the columns I mentioned earlier are `utf8mb4`. My biggest concern was to make sure it doesn't get changed to just `utf8` for whatever reason. Do you think I should still add `modelBuilder.HasCharSet("utf8mb4")` to make sure they don't get changed to `utf8` or that is not necessary and they shouldn't change?

**Comment by lauxjpn** [comment]
If you don't call `modelBuilder.HasCharSet()` explicitly, Pomelo calls `modelBuilder.HasCharSet("utf8mb4")` implicitly. So if you are using `utf8mb4` for all your columns as a default, there is no need for you to call it (but there are no negative effects either if you do).

However, as always with migrations, test them first locally, before applying them to your production system. Just to be safe.

**Comment by B-DAP** [comment]
Thanks for the info. I think this solves my problem now. I will close this ticket.

**Comment by tuanbs** [comment]
I got the same issue after migrating from 3.1 to 5. The new migration removes all "CHARACTER SET utf8mb4":

<img width="1392" alt="Screen Shot 2021-08-12 at 11 51 39 am" src="https://user-images.githubusercontent.com/4801395/129154015-e31c8d72-30fe-427e-af9d-4b8c8eeddb0a.png">

As suggested above, it has no effect and the "CHARACTER SET utf8mb4" is set implicitly. So I applied the new migration with the test DB. The test DB is updated successfully. But when I ran the project on the test DB, I got error. Fortunately, I just applied the new migration with the test DB only, not the dev or prod DB.

Also, as we can see the above image, the table "__EFMigrationHistory" uses "CHARACTER SET utf8mb4" explicitly for some columns, even though it's said it's already set implicitly. So, I think the new migration causes the error.
