### ISSUE TITLE
Auto cancel execution when the query timeout?

### ISSUE THREAD

**Issue by Flithor** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1438]
After the execution of some heavy queries timeout, the MySQL service still continues to execute without cancel.
Any options can config this behavior?

I've found this: https://stackoverflow.com/a/35487125/6859121

**Comment by lauxjpn** [comment]
[MySQL .NET Connection String Options](https://mysqlconnector.net/connection-options/) contain the `DefaultCommandTimeout`:

> The length of time (in seconds) each command can execute before the query is cancelled on the server, or zero to disable timeouts. See the note in the [Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtimeout) for more explanation of how this is determined.

If that is not enough, there is also `CancellationTimeout`:

> The length of time (in seconds) to wait for a query to be canceled when `MySqlCommand.CommandTimeout` expires, or zero for no timeout. If a response isn’t received from the server in this time, the local socket will be closed and a `MySqlException` will be thrown.

Instead of using the `DefaultCommandTimeout` connection string option directly, you could also set it using the context option `CommandTimeout()`:

```c#
optionsBuilder.UseMySql(
    connectionString,
    serverVersion,
    options => options.CommandTimeout(30))
```

---

There is currently no option for Pomelo, to set the `max_execution_time` variable directly. So if the previous options are not sufficient for your case, you might want to set the `max_execution_time` variable yourself after the connection was opened, or when the statement is about to being executed (see [Interceptors](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors)).

**Comment by lauxjpn** [comment]
@Flithor Is there anything left for us to do, or are the provided solutions sufficient?

**Comment by lauxjpn** [comment]
@Flithor Since we haven't heard back from you, we are closing this one.
