### ISSUE TITLE
Generated migration sql of wrong syntax with longtext when upgrading into 5.0

### ISSUE THREAD

**Issue by Liu233w** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1461]
### Steps to reproduce
I have created a repo to reproduce the problem, see https://github.com/Liu233w/mysql-issue-reproduction

### The issue
In this project, the first migration is created in version 3.1.1, and the field `LongString` in entity `Entity` has type `longtext CHARACTER SET utf8mb4` in `20210626155013_Init.Designer.cs`. After upgrading into version 5.0 and creating a new migration, the `oldType` of that field in `20210626162110_Upgrade.cs` becomes `longtext CHARACTER SET utf8mb4(5000)`.

That problem also causes malfunction when using `dotnet ef migrations script` or doing migration at project startup. https://github.com/Liu233w/mysql-issue-reproduction/blob/master/script.sql shows the output after running `dotnet ef migrations script` with the migration `20210626162110_Upgrade`.

### Further technical details

MySQL version: 8.0
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 5.0.0
Microsoft.AspNetCore.App version: Not needed to reproduce the problem

Other details about my project setup:

**Comment by lauxjpn** [comment]
@Liu233w Thanks for uploading the reference project.

The recommended way in Pomelo 3.x to configure the `DbContext` was to use the option `.CharSetBehavior(CharSetBehavior.NeverAppend)` (see [3. Services Configuration](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/tree/3.2-maint#3-services-configuration) of the `3.2-maint` branch), because all other options were obsolete (they have always been kind of a hack). Using this option would not have explicitly added the `CHARACTER SET utf8mb4` part to the type. The `CharSetBehavior` option got removed for 5.0. In 5.0, character sets can be controlled with the `HasCharSet()` Fluent API methods.

---

To solve the issue, you have multiple options:

You can just manually modify the `Up()` and `Down()` scripts and move on.

The other way is to rollback to your Pomelo 3.x state (with no model changes yet) and then add the `CharSetBehavior(CharSetBehavior.NeverAppend)` call.
Then add a migration (e.g. called `CharSetBehavior`), that only contains this one change.
The result will remove the explicit `CHARACTER SET utf8mb4` part from the types.
Then do the upgrade to 5.0 (don't forget to also update the `dotnet-ef` tool).
The result will be a `utf8mb4` character set for your columns after all, because it is the default charset in 5.0 as long as you don't specify anything else in your model (using the 5.0 `HasCharSet()` Fluent API call).

Here is a test project:

<details>
<summary>Program.cs</summary>

```c#
//#define POMELO5

using System;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
using Pomelo.EntityFrameworkCore.MySql.Storage;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int IceCreamId { get; set; }
        
        [StringLength(5000)]
        public string Name { get; set; }
    }
    
    public class Context : DbContext
    {
        public DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1456_01";
                var serverVersion = ServerVersion.AutoDetect(connectionString);
#if !POMELO5
                optionsBuilder.UseMySql(
                        connectionString,
                        options => options
                            .ServerVersion(serverVersion)
                            .CharSetBehavior(CharSetBehavior.NeverAppend)) // <-- recommended option in 3.x
#else
                optionsBuilder.UseMySql(connectionString, serverVersion)
#endif
                    .UseLoggerFactory(
                        LoggerFactory.Create(
                            configure => configure
                                .AddConsole()
                                .AddFilter(level => level >= LogLevel.Information)))
                    .EnableSensitiveDataLogging()
                    .EnableDetailedErrors();
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>(
                entity =>
                {
                    entity.HasData(
                        new IceCream {IceCreamId = 1, Name = "Vanilla"});
                });
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var iceCream = context.IceCreams.Single();

            Trace.Assert(iceCream.IceCreamId == 1);
        }
    }
}
```

</details>

The SQL script afterwards will look like the following:

<details>
<summary>Generated SQL script</summary>

```sql
ALTER DATABASE CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MigrationId` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `ProductVersion` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
) CHARACTER SET utf8mb4;

START TRANSACTION;

CREATE TABLE `IceCreams` (
    `IceCreamId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext CHARACTER SET utf8mb4(5000) NULL,
    CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
);

INSERT INTO `IceCreams` (`IceCreamId`, `Name`)
VALUES (1, 'Vanilla');

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210626233223_Initial', '5.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE `IceCreams` MODIFY COLUMN `Name` longtext NULL;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210626235228_CharSetBehavior', '5.0.7');

COMMIT;

START TRANSACTION;

ALTER TABLE `IceCreams` MODIFY COLUMN `Name` varchar(5000) CHARACTER SET utf8mb4 NULL;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210626235503_Upgrade', '5.0.7');

COMMIT;
```

</details>

The change from `longtext` to `varchar(5000)` is correct and expected, because you specified an explicit length of 5000 characters for the string and `longtext` does not have a character limit (3.x handled this incorrectly and we fixed it for 5.0).
If you want a `longtext`, remove the `[StringLength(5000)]` data annotation.

**Comment by Liu233w** [comment]
Hi @lauxjpn , thanks for your reply!

It seems like that MySql does not recognize the syntax of `longtext CHARACTER SET utf8mb4(5000)` because of the `(5000)` at the end. And your generated SQL script also has that problem. 

BTW, I have tested your solution in the repo (in branch [try-fix-1](https://github.com/Liu233w/mysql-issue-reproduction/tree/try-fix-1)), and the syntax error persists.

**Comment by lauxjpn** [comment]
Your `try-fix-1` branch looks good to me. Where in there is the issue for you?

> And your generated SQL script also has that problem.

Not really. It uses your current situation as the starting point (where the issue is already present). It then fixes the issue.
My approach does not retroactively change already existing migrations (but you can do that manually).

---

You can also just change the column type to `varchar(5000)` or `longtext` (replacing the `StringLength` data annotation) for your property before upgrading, instead of letting the (faulty) 3.x implementation figure it out:

```c#
[Column(TypeName = "varchar(5000)")]
public string LongString { get; set; }

// or:

[Column(TypeName = "longtext")]
public string LongString { get; set; }
```

But you should still apply `CharSetBehavior(CharSetBehavior.NeverAppend)`.

**Comment by Liu233w** [comment]
I mean this part:
![image](https://user-images.githubusercontent.com/16333687/123541799-a691da80-d789-11eb-97cf-b28de2728792.png)

**Comment by Liu233w** [comment]
When doing migration, it shows error like `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(5000) NULL`

**Comment by lauxjpn** [comment]
Yeah, but that is just the faulty implementation due to not using `CharSetBehavior(CharSetBehavior.NeverAppend)` and using the `StringLength` annotation.

My previously outlined approaches (e.g. the `[Column(TypeName = "varchar(5000)")]` one) should work.
But depending on your setup, you might want to adjust a previous migration (and the current snapshot) first.

**Comment by Liu233w** [comment]
Well, I fixed it by modifying the column type in file `20210626155013_Init.Designer.cs` after creating the migration of changing char set, although I don't know if it is safe to modify a migration being already applied to the database.

**Comment by lauxjpn** [comment]
> I don't know if it is safe to modify a migration being already applied to the database.

It's fine. The only thing that matters after generating the migration in your case are the `Up()` and `Down()` scripts (and the current snapshot file).

**Comment by skoruba** [comment]
How to solve this issue with the latest version of this package? 

I can see that fix - use following method - `CharSetBehavior(CharSetBehavior.NeverAppend)` - but this option was probable removed.

Thank you

**Comment by mguinness** [comment]
> How to solve this issue with the latest version of this package?

Can you confirm if you're using 5.0 or 6.0?  It helps if you can give us the specific version.

Please share your model and any fluent API methods, are you using annotation `[Column(TypeName = "longtext")]`?

> I can see that fix - use following method - `CharSetBehavior(CharSetBehavior.NeverAppend)` - but this option was probable removed.

Yes `CharSetBehavior` was removed in 5.0 and replaced with `HasCharSet()` fluent API methods.

**Comment by skoruba** [comment]
Sorry, I use version `5.0.3`, not 6.0 yet. :)

I use following definition:

```
public class Todo {
     public string Value { get; set; }
}
```

```
 modelBuilder.Entity<Todo>(todo =>
            {
                todo.Property(x => x.Value).HasMaxLength(4000).IsRequired();
            });
```

I use this definition for multiple Db Providers - MySQL, SQLServer, PostgreSQL.

**Comment by lauxjpn** [comment]
@skoruba Please post the full exception that is being thrown and the generated SQL [logged](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics) by EF Core.
