### ISSUE TITLE
Scaffolding not working

### ISSUE THREAD

**Issue by SilverioMiranda** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#152]
I run this command with and get no result

See console output 
![image](https://cloud.githubusercontent.com/assets/1939153/21212332/becbc59c-c272-11e6-9bd4-f15a8e68e8eb.png)

### Further technical details

MySQL version: 5.7.15
Operating system: Windows 10 x64
Pomelo.EntityFrameworkCore.MySql version:  "1.1.0"

Other details about my project setup:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.1.0"
    },
    "Pomelo.EntityFrameworkCore.MySql": "1.1.0",
    "Pomelo.EntityFrameworkCore.MySql.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final"
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}

```

**Comment by mguinness** [comment]
One possibility is that you have tables w/ no PK.  If however they do, try `--table <schema.table>` option to scaffold an individual table to see if that works.  Also see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/149#issuecomment-266254544 regarding the verbose flag.

**Comment by fabs-rodriguez** [comment]
I have the same problem. All my tables have PK's though. However it appears to be doing this on tables that have Foreign Keys...

I'm using Pomelo 1.1.1
EF Core 1.1 / .Net Core 1.1 Web Api
Visual Studio 2017

**Comment by mguinness** [comment]
@fabs-rodriguez Use [this schema](http://www.mysqltutorial.org/mysql-sample-database.aspx) that has FK's and try to scaffold that.  If that works, then there must be something specific to your schema that'll need investigation.

**Comment by JanBN** [comment]
I have the same problem. What is strange that on another computer (at work) it works. But on my home pc it does nothing. On Monday I will try it at work again.

However I run this:
`C:\.Net Core\EFTest MySql\EFTest>dotnet ef dbcontext scaffold "Server=localhost;User Id=root;Password=;Database=bcd" "Pomelo.EntityFrameworkCore.MySql"  -o
 Mode2 --verbose` with verbose option

and this is the output:

> c:\.Net Core\EFTest MySql\EFTest>dotnet ef dbcontext scaffold "Server=localhost;User Id=root;Password=;Database=bcd" "Pomelo.EntityFrameworkCore.MySql"  -o Mode2 --verbose
> Using project 'c:\.Net Core\EFTest MySql\EFTest\EFTest.csproj'.
> Using startup project 'c:\.Net Core\EFTest MySql\EFTest\EFTest.csproj'.
> dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\jp\AppData\Local\Temp\tmp9E9.tmp /verbosity:quiet /nologo "c:\.Net Core\EFTest MySql\EFTest\EFTest.csproj"
> dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\jp\AppData\Local\Temp\tmpC7A.tmp /verbosity:quiet /nologo "c:\.Net Core\EFTest MySql\EFTest\EFTest.csproj"
> dotnet build "c:\.Net Core\EFTest MySql\EFTest\EFTest.csproj" /verbosity:quiet /nologo
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:02.42
> dotnet exec --depsfile "c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\EFTest.deps.json" --additionalprobingpath C:\Users\jp\.nuget\packages --runtimeconfig "c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\EFTest.runtimeconfig.json" C:\Users\jp\.nuget\packages\microsoft.entityframeworkcore.tools.dotnet\1.0.0\tools\netcoreapp1.0\ef.dll dbcontext scaffold "Server=localhost;User Id=root;Password=;Database=bcd" Pomelo.EntityFrameworkCore.MySql -o Mode2 --assembly "c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\EFTest.dll" --startup-assembly "c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\EFTest.dll" --project-dir "c:\.Net Core\EFTest MySql\EFTest\\" --content-root "c:\.Net Core\EFTest MySql\EFTest\\" --data-dir "c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\\" --verbose --root-namespace EFTest
> Using assembly 'EFTest'.
> Using startup assembly 'EFTest'.
> Using application base 'c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0'.
> Using content root 'c:\.Net Core\EFTest MySql\EFTest\'.
> Using root namespace 'EFTest'.
> Using project directory 'c:\.Net Core\EFTest MySql\EFTest\'.
> Using data directory 'c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\'.

It won't continue after **Using data directory 'c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\'**

**Comment by JanBN** [comment]
I have installed another version of MySQL/MariaDB and it works.
It does not work for this version:

> Server version: 10.1.9-MariaDB

It works for this version:

> Server version: 10.1.22-MariaDB

Hope it helps somebody.

**Comment by dknoodle** [comment]
I am having the exact same issue getting to "Using data directory ..." and then it just hangs and never does anything.  I am running MySQL Community Edition 5.7.18.

Has anyone made any other progress on this?

**Comment by dknoodle** [comment]
After reading DanBN's comments about the different Database versions resolving the issues I imported the DB into an Azure MySQL database.  This pushed me past the hang at "Using data directory..." but now I am getting an object reference error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at MySql.Data.MySqlClient.MySqlConnection.CloseDatabase()
   at MySql.Data.MySqlClient.MySqlConnection.DoClose()
   at MySql.Data.MySqlClient.MySqlConnection.Dispose(Boolean disposing)
   at System.Data.Common.DbConnection.Dispose()
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, Table
SelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory.Create(String connectionString, TableS
electionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlScaffoldingModelFactory.Create(String connectionString, Ta
bleSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineeringGenerator.GetMetadataModel(ReverseEngineering
Configuration configuration)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineeringGenerator.GenerateAsync(ReverseEngineeringCon
figuration configuration, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContextAsync(String provider, String conn
ectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataA
nnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<ScaffoldContextImpl>d__22.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

**Comment by caleblloyd** [comment]
@dknoodle are you using Pomelo 1.1.2?

**Comment by dknoodle** [comment]
@caleblloyd - Yes I am.

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.1" />
    <PackageReference Include="Pomelo.Data.MySql" Version="1.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="1.1.2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.2" />
    
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>

**Comment by dknoodle** [comment]
@caleblloyd - I'm pulling this apart one step at a time.  I pulled in the Pomelo.EntityFrameworkCore.MySql source code into the project and it gave me an Access Denied error.  I found the parameter names I needed for user/pass were incorrect.

In some of my testing I accidentally ran it with a blank database and it created the DbContext class and ran without issue.  The DB I am trying to model though has 460 tables.  When I pointed it at the correct DB with the correct login it now hangs again at "Using Data Directory..." just as it did for @JanBN 

I suspect the Object reference error was due to the incorrect user/pass parameter names.  It would be good to have this output a better Auth failure exception rather than the Object reference error.  That or the current repository code already handles this better than the NuGet package as I got an actual Access Denied with the repository code directly in the project.

**Comment by dknoodle** [comment]
@caleblloyd - Looks like it may actually be working and running.  I used Sysinternals Process Monitor to watch all the network traffic and I can see connections starting and stopping to the DB server.  I let it run over night last night and it never finished so I will go ahead and let it run for a few hours again.

Perhaps this is a limitation of Entity Framework Scaffold but is there any way to get it to output what table it's processing?  Even with --verbose it just sits at the "Using data directory..." message like it's hung.  I can see the dotnet.exe process making network connections and I ran some sys queries on the DB so I can see it requesting schema data for each table.

Based on the average time it takes to query a schema and process the table (approx 43 seconds per table on average) I estimate it will take nearly 6 hours to complete the scaffolding.  Assuming nothing goes wrong anywhere.  Is there any way to speed this up or know for sure if it's working?

**Comment by dknoodle** [comment]
Looks like some data type mappings are missing.  It finished much sooner than I expected (still took 4+ hours) but missed mapping date and timestamp columns on all the tables.  It spit out over 1,200 lines of errors, primary for timestamp and date.  Looking deeper at the data types in the DB and the models created it's handling "datetime" correctly but not "date" or "timestamp".

1) Could not find type mapping for column 'catalogsearch_query.updated_at' with data type 'timestamp'. Skipping column. warn: Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory[6]
Could not find type mapping for column 'catalogsearch_query.updated_at' with data type 'timestamp'. Skipping column.

2) Could not find type mapping for column 'catalogrule_product_price.rule_date' with data type 'date'. Skipping column. warn: Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory[6]

I had a lot of tables where it says it couldn't find the primary key for a table.  I don't think that should prevent the table being mapped, should it?

3) warn: Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory[7]
Unable to identify the primary key for table 'catalog_category_anc_categs_index_idx'.
Unable to generate entity type for table 'catalog_category_anc_categs_index_idx'.

4) Could not find type mapping for column 'xtento_trackingimport_source.ftp_type' with data type 'enum('','ftp','ftps')'. Skipping column. warn: Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory[6]
Could not find type mapping for column 'xtento_trackingimport_source.ftp_type' with data type 'enum('','ftp','ftps')'. Skipping column.

Any idea how to handle an Enum data type in MySQL?  Looks like it has the values needed in the column details but needs an Enum map to be created.

**Comment by mguinness** [comment]
> I had a lot of tables where it says it couldn't find the primary key for a table. I don't think that should prevent the table being mapped, should it?

It's in the backlog for EF, see https://github.com/aspnet/EntityFramework/issues/5719.

**Comment by caleblloyd** [comment]
> still took 4+ hours

That's much longer than I would expect, I'm curious as to what commands it was executing.  Was your latency high?

> Any idea how to handle an Enum data type in MySQL

Enums are not natively supported by this library right now.  EF does not provide a mechanism to keep Enum values in-sync on the server side.  The closest you can get is to create the mapping in C# and have it backed by an `int` or `tinyint` in MySQL [example](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Models/DataTypes.cs#L137-L145)

> Perhaps this is a limitation of Entity Framework Scaffold but is there any way to get it to output what table it's processing?

Since Entity Framework upstream is not logging much information, we'd have to look at putting custom logging in.  Sounds like a good idea.

Our [scaffolding test](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/scripts/scaffold.sh) currently covers all data types, but does not cover some of the other things you are running into - default values, different primary key scenarios, etc.

From what I understand, most of the core dev team aren't heavy scaffolding users for advanced cases such as these.  We'd be more than happy to take contributions from the community who need advanced scaffolding use cases.

**Comment by dknoodle** [comment]
> That's much longer than I would expect, I'm curious as to what commands it was executing. Was your latency high?

According to my network logs, the latency was around 4-15ms.  When I was watching it the connection requests burst up to 7-15Mbps on a 75Mbps internet connection.  I don't think that was the issue.

> Enums are not natively supported by this library right now. EF does not provide a mechanism to keep Enum values in-sync on the server side. The closest you can get is to create the mapping in C# and have it backed by an int or tinyint in MySQL example

I added Type Mappings for "date" and "timestamp" to the MySqlTypeMapper.cs class and ran it again over night.  Now I only have 10 tables with 3 different Enums to manually edit.  I can totally live with that over 460 tables!  It also had a number of Index and Temp tables with no PK but I think there is only one table I actually need to manually 

> Our scaffolding test currently covers all data types, but does not cover some of the other things you are running into - default values, different primary key scenarios, etc.

I think your missing a couple, I will do a pull request with my changes once I do a little more testing.  I added "date" and "timestamp" which fixed hundreds of conversion errors for me.

Awesome library, I really appreciate all the work the core team put into this!  Thanks for all the feedback and input as well!

**Comment by JanBN** [comment]
@dknoodle  could you please share your mappings ? Timestamp and date would be handy also for me.

Anyway I have run scaffold again and this time with no success. So I have installed several MariaDB/MySql servers. And it seems if there are none databases on the server, just one (maybe two), it works. If I add another db it stops on the:

> `Using data directory bla bla`

I'm not sure If I'm doing something wrong because this is strange. 

@dknoodle maybe give it a try to have just one db on the server.

**Comment by dknoodle** [comment]
@JanBN - The changes are incredibly simple to make.  I pulled in the repository source code and added three lines.

Inside Microsoft.EntityFrameworkCore.Storage.Internal.MySqlTypeMapper

Added line 51:
`private readonly RelationalTypeMapping _date6 = new RelationalTypeMapping("datetime(6)", typeof(DateTime), DbType.Date);`

Added lines 110 & 111:
```
{ "timestamp", _dateTime6 },
{ "date", _date6 },
```

This added the mapping for the timestamp and date types.  I haven't submitted a pull request yet because I wasn't 100% sure if there was something else somewhere that also needed to be modified along with this.  My testing was very limited but in my scenario it worked perfectly and resolve 98% of my issues.  The rest of the issues were related to tables with no Primary Key.  As it turned out, they were all temp and indexing tables that I didn't need anyway.

I was running on a MySql DB with only a single database.  That one database has 460 tables.

**Comment by fauriemma** [comment]
Hi,
I have same issue but after analyze mysql-slow-query i found a solution.

In my case problem is that i have two schema with different name but with same tables definition.

Pomelo scaffold execute a quary that retrieve table information as:

SELECT `CONSTRAINT_SCHEMA`,
        `CONSTRAINT_NAME`,
        `TABLE_NAME`,
        `COLUMN_NAME`,
        `REFERENCED_TABLE_NAME`,
        `REFERENCED_COLUMN_NAME`,
        (SELECT `DELETE_RULE` FROM `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` WHERE `REFERENTIAL_CONSTRAINTS`.`CONSTRAINT_NAME` = `KEY_COLUMN_USAGE`.`CONSTRAINT_NAME`) AS `DELETE_RULE`
FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE`
WHERE `CONSTRAINT_SCHEMA` = 'IRVAT_AgriTrack_Data'
                AND `TABLE_SCHEMA` = 'IRVAT_AgriTrack_Data'
                AND `TABLE_NAME` = '__EFMigrationsHistory'
                AND `CONSTRAINT_NAME` <> 'PRIMARY'
        AND `REFERENCED_TABLE_NAME` IS NOT NULL;

in this part of subquery 
SELECT `DELETE_RULE` FROM `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` WHERE `REFERENTIAL_CONSTRAINTS`.`CONSTRAINT_NAME` = `KEY_COLUMN_USAGE`.`CONSTRAINT_NAME`

is omitted SCHEMA_NAME as WHERE filter and in my case query fails because subquery return more than one result.

If you drop one of two similar schemas, or rename all constraint with different name, scaffold work without any problem!!!

**Comment by bluee** [comment]
This bug should be re-opened

@fauriemma  found the issue. You can easily replicate it by duplicating your database schema. Scaffolding will fail as Pomeo does not like duplicate constraint names even though they are in another schema.

A work around is to find all your duplicate names here and rename/remove them:

SELECT` CONSTRAINT_NAME, COUNT(*) AS C FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS GROUP BY CONSTRAINT_NAME HAVING C>1

**Comment by mguinness** [comment]
PR https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/386 should resolve the issue after it gets merged.
