### ISSUE TITLE
There is already an open DataReader associated with this Connection

### ISSUE THREAD

**Issue by alexknips** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#158]
I currently get the exception for some background tasks
```
Exception: Exception caught: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.ni.dll 
("There is already an open DataReader associated with this Connection which must be closed first."). 
Exception caught: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.ni.dll ("There is 
already an open DataReader associated with this Connection which must be closed first.")
```

Is there a solution with Multiple Active Results?

**Comment by caleblloyd** [comment]
MySQL does not support Multiple Active Result Sets, so we have coded around this to fully read a result set before moving onto the next one.

Sometimes this exception is actually caused by an inner exception.  So this is either an inner exception that is getting masked by this message or a bug.

Can you increase your logging to include a full stack trace including inner exceptions?

**Comment by caleblloyd** [comment]
For reference: queries over each connection are:

- Serialized in [MySqlRelationalCommand](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlRelationalCommand.cs#L69-L80)
- Non-Readers are unlocked after execution, also in [MySqlRelationalCommand.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlRelationalCommand.cs#L121-L130)
- Readers are unlocked once they are consumed in [SynchronizedMySqlDataReader.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/SynchronizedMySqlDataReader.cs#L209-L215)

It _should not_ be possible to open two readers at the same time if everything is queried through `MySqlRelationalCommand.cs`.  If the connection is accessed from non-library code, then it is possible.

We need to identify:

1. Is there's a bug in the library where the connection is accessed not using `MySqlRelationalCommand.cs`? (if so need to fix that code to use `MySqlRelationalCommand.cs`)
2. Is this exception getting triggered by some other inner exception? (if so we need to fix exception handling)

**Comment by alexknips** [comment]
Thanks for the ideas. I will come back if I know more about possible inner exceptions.

**Comment by alexknips** [comment]
Ok. I could not get any more inner exception details yet. But I think the issue might be more connected to the way the DbContext is handled.
I am using Hangfire (also talking to them on this issue) to access Mysql through a DbContext object. I suspect that the DbContext is recreated through de-serialization and then the connection is opened again. Might this explain the error message or am I heading down the wrong path here?

**Comment by caleblloyd** [comment]
If you configure the DbContext with a Connection String in the DbContext's `OnConfiguring` method ([example](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/AppDb.cs#L57)) then you should be in good shape.  Also make sure to create the DbContext in your background job, don't reference an existing one that's active (if you can).

**Comment by alexknips** [comment]
thanks for your help

**Comment by eyal7773** [comment]
I would like to advice what helped me (even that this is closed ticket, maybee someone will see it) :

After update to Pomelo 2.1.1 this code fail : 
`
  var currentOriginPortfolio = _context.FamilyPortfolios.Where(x => x.FamilyId == customer.Family.ID);
                if (currentOriginPortfolio.Count() >= 1)
                {

                    foreach(FamilyPortfolio fp in currentOriginPortfolio)
                    {
                        fp.PortfolioTypes = PortfolioTypes.Archive;
                        if (fp.Name == "original")
                            fp.Name = "archive";

                        fp.UpdatedAt = DateTime.Now;
                        _context.SaveChanges();
                    }
                } 
`

The issue was that I didn't use the "ToList()" on the first command, so it is 2 quaries simulany on the same context.

So to fix it I change the first line to :  

` var currentOriginPortfolio = _context.FamilyPortfolios.Where(x => x.FamilyId == customer.Family.ID)**.ToList()**;`

hope it will help someone.
