### ISSUE TITLE
why needs to set MySqlServerVersion in UseMySql? it's simple to get mysql version with connect string and ado.net

### ISSUE THREAD

**Issue by bthulu** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1603]
### Steps to reproduce
i have an app which will be deployed to many customers with their mysql, and the version ranges from 5.7.x to 8.0.x.
i prefer to use ef core rather than dapper, is just because it supports to deploy to various dbs and various db versions without change my code.
i know i can use appsettings.json to specify a version without hard coded, but it will make config file difficult to control because every customer has its own versions.
another way is to connect to mysql to get version before app init. but if sometimes failed to connect to mysql, app stopped, how to debug? set version hard coded, and remember to change it back when network normal? bug if i forgot to change it back? so if pomelo can do this, it can connect to mysql to get version lazy while really needs then app can start even if network breaks.

**Comment by lauxjpn** [comment]
@bthulu We already support server version auto detection:

_From [Getting Started: 2. Services Configuration](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#2-services-configuration):_

```c#
// [...]

// Replace with your server version and type.
// Use 'MariaDbServerVersion' for MariaDB.
// Alternatively, use 'ServerVersion.AutoDetect(connectionString)'.
// For common usages, see pull request #1233.

// [...]
```

The interesting part for you here is: `Alternatively, use 'ServerVersion.AutoDetect(connectionString)'.`

In pretty much every sample code I post in issues here, you can see this in action, e.g. in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1600#issuecomment-1013953253:

```c#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1600";
    var serverVersion = ServerVersion.AutoDetect(connectionString); // <-- use auto detection

    optionsBuilder
        .UseMySql(connectionString, serverVersion)
        .UseLoggerFactory(
            LoggerFactory.Create(
                b => b
                    .AddConsole()
                    .AddFilter(level => level >= LogLevel.Information)))
        .EnableSensitiveDataLogging()
        .EnableDetailedErrors();
}
```

---

The server version is necessary, since older versions of MySQL/MariaDB might not support specific features that are needed for some of the more advanced EF Core query translations.

**Comment by bthulu** [comment]
@lauxjpn 
it's commented, i don't see it.
maybe comment it as follows, since it's more common.
```
        // Alternatively, use 'new MySqlServerVersion(new Version(8, 0, 27))'.
        // For common usages, see pull request #1233.
        var serverVersion = ServerVersion.AutoDetect(connectionString);
```

**Comment by lauxjpn** [comment]
@bthulu The decision was made to use the explicit version as the default because:

* Many complex queries require very new MySQL versions, and a version difference between your local development machine setup and your production setup could lead to queries suddenly failing in production, if your development server version is newer
* It has no overhead

The `ServerVersion.AutoDetect()` option is not just shown in our sample code on the front page, but also mentioned in the wiki under [Configuration-Options: Mandatory parameters - Server version](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Configuration-Options#server-version):

> ### Server Version
> 
> Pomelo.EntityFrameworkCore.MySql is compatible with a variety of MySQL compatible database server implementations over multiple versions. To choose the right syntax and available feature set for the server implementation at hand, specify the exact server version you are running.
> 
> Either set the server version directly using the `MySqlServerVersion` and `MariaDbServerVersion` classes, or indirectly by calling the static `ServerVersion.AutoDetect()` or `ServerVersion.Parse()` methods.

The option should also be shown via IntelliSense when typing `.UseMySql()`:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/462c142c732ff550be3dec0aca21a8beea174b1f/src/EFCore.MySql/Extensions/MySqlDbContextOptionsBuilderExtensions.cs#L35-L49
