### ISSUE TITLE
6.0.1 affected by bug in MySqlConnector 2.13 fixed in 2.14

### ISSUE THREAD

**Issue by kampilan** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1609]
The bug introduced in MySqlCOnnector 2.13 and fixed in 2.14 causing problems in 6.0.1, at least for me anyways. I reverted back to 6.0.0.

Thanks
Jim

**Comment by kampilan** [comment]
I stand corrected 2.14 does not fix my issue. Only reverting to 6.0.0 does. In will close this for now until I have some more details to share.

**Comment by mguinness** [comment]
If you could share the exception or details of the bug that would help us determine if the issue is in Pomelo or MySqlConnector.  FWIW, `Pomelo 6.0.0` has a dependency for `MySqlConnector 2.0.0` and `Pomelo 6.0.1` has a dependency for `MySqlConnector 2.1.2` so you must have specified the newer versions of MySqlConnector yourself.

**Comment by kampilan** [comment]
I just figured that out, ;) It is a weird issue that I am now convinced is unrelated to Pomelo or MySqlConnector. I'm still investigating. Thanks for your help and sorry for the false alarm.
