### ISSUE TITLE
Support for int IndexOf(string value, int startIndex)

### ISSUE THREAD

**Issue by jespersh** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1625]
### Currently
We Currently have an implementation of `int IndexOf(string value)`  calling `column.IndexOf("#") <= 1` that gets (roughly) translated into `
```sql
LOCATE('#', `j`.`column`) - 1) > 1
```

Implementing `int IndexOf(string value, int startIndex)` means we can use the form `LOCATE('#',column,X)=0` for `column.IndexOf("#", X) == -1`.
A way to currently achieve this implementation is to use `Substring(1).IndexOf("#") == -1` which however results in a fairly interesting:
```sql
(LOCATE('#', SUBSTRING(`j`.`column`, 1 + 1, CHAR_LENGTH(`j`.`column`))) - 1) = -1
```

**Comment by mguinness** [comment]
Yes, currently `int string.IndexOf(string value, int startIndex)` isn't translated into [LOCATE(substr,str,pos)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_locate) yet.  This is a community based project and we welcome code contributions via pull requests.

You can take a look at the existing implementation as a guide to adding the overload in [MySqlStringComparisonMethodTranslator](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlStringComparisonMethodTranslator.cs).

**Comment by LeaFrock** [comment]
@mguinness  I wanna contribute to this. Would you please help me review and accomplish my PR #1645 ?

**Comment by mguinness** [comment]
@ajcvickers @roji Is there a reason why the start index parameter of [IndexOf()](https://docs.microsoft.com/en-us/dotnet/api/system.string.indexof#system-string-indexof(system-string-system-int32)) isn't translated for [SQL Server](https://docs.microsoft.com/en-us/ef/core/providers/sql-server/functions) or [Postgres](https://www.npgsql.org/efcore/mapping/translations.html)?  Is it because there is a workaround, like substring?

**Comment by roji** [comment]
@mguinness I don't think there's any particular reason - probably just nobody asked for it... I can see overloads of CHARINDEX (SQL Server) and STRPOS (PG) which accept the additional starting position parameter.

**Comment by roji** [comment]
@mguinness @lauxjpn @LeaFrock it turns out this actually was implemented for SQL Server in https://github.com/dotnet/efcore/pull/26623, for 7.0.0-preview.1. There's a specification test for it as well, but since it was using a top-most projection, the test can client-eval and always passes regardless of whether a provider implements translation support or not. I opened https://github.com/dotnet/efcore/pull/28031 to improve the tests.

Note that SQLite and PostgreSQL do not have a function which accepts a start position parameter.

**Comment by LeaFrock** [comment]
Thanks for the PR from @roji , and based on it, I've created another PR #1652  to optimize the previous translation.

**Comment by mguinness** [comment]
Wiki updated as requested.  Since you're a collaborator, you should see an Edit button on the page to allow you to edit the markdown.

**Comment by LeaFrock** [comment]
> Wiki updated as requested. Since you're a collaborator, you should see an Edit button on the page to allow you to edit the markdown.

Thanks for your update. I'm just a normal contributor 😄 and the edit button is hidden to me.
