### ISSUE TITLE
Expose Connection String Builder to DI for use in Type Mapper

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#163]
Right now we create a Connection String builder in [UseMySql()](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/3b600717db2710eec0c3da3c316d5e8c3971fe13/src/Pomelo.EntityFrameworkCore.MySql/Extensions/MySqlDbContextOptionsExtensions.cs#L25-L29).

Expose this Connection String Builder via DI so that `TypeMapper` can make use of it.  Adjust TypeMapper types based off settings for:

- TreatTinyIntAsBool in #153 
- OldGuids in #159

**Comment by Kagamine** [comment]
@caleblloyd I think `datetime(6)` issue still can be solved by this way, we could start a MySqlConnection to get mysql version when .UseMySql() has been invoked.

**Comment by caleblloyd** [comment]
Yes, but we would want to cache the result based off the connection string so it doesn't get opened every time `.UseMySql` is called.  This is called once per DbContext.

**Comment by m-wilczynski** [comment]
**Quick note**
 I just found out that using `HasColumnType("binary(16)")` will fail if you left generating UUID/GUID to database. 
It will fail because `UUID()` function of MySQL generates string based identifier (go check `SELECT UUID()` on any MySQL DB), instead of binary one and therefore, it will fail on attempt to fit it inside `BINARY(16)` column type.

**Comment by Kagamine** [comment]
@caleblloyd  What is the default behavior about TreatTinyAsBoolean?
