### ISSUE TITLE
UseMySql( DbConnection ) extension expects the connection to be closed

### ISSUE THREAD

**Issue by kampilan** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#169]
In MySqlDbContextOptionsExtensions.UseMySql extention method that takes a DbConnection, the code below expects (demands actually) that the connection be closed

            var csb = new MySqlConnectionStringBuilder(connection.ConnectionString)
            {
	            AllowUserVariables = true,
	            UseAffectedRows = false
            };

            connection.ConnectionString = csb.ConnectionString;

An Exception is thrown when the connection string is is set on the open connection.

 https://docs.microsoft.com/en-us/ef/core/saving/transactions 

This article explains how to share connections and transactions. This technique is not possible with your MySQL implementation.

Thanks
Jim

**Comment by Kagamine** [comment]
Which version are you using?

**Comment by caleblloyd** [comment]
We should remove the code that sets the connection string if a connection is passed in 

We should document that users need to set `AllowUserVariables=true;UseAffectedRows=false` in their connection string if they are going to pass a connection

**Comment by Kagamine** [comment]
Can we detect the connection? if the connection lack of some params then create a new one.

**Comment by kampilan** [comment]
I agree with Caleb. The code should be removed and the requirements documented. The connection string can still be checked for the required parameters even if the connection is open. At that point you could throw an exception. Generally I don't think you should change connection string behind the scenes. It usually leads to problems.

**Comment by kampilan** [comment]
A little more research ...
The default value for UseAffectedRows is false. The only way it could be true is that the caller specifically set it to true. Quietly setting it back to false is not a good idea. If it is essential that it be set to false, an Exception needs to thrown whether the connection string or an actual connection was supplied.

**Comment by Kagamine** [comment]
UseAffectedRows must be false in EF, otherwise it will throw an exception while updating.

**Comment by kampilan** [comment]
Understood. Then an Exception should be thrown if it is set to true. Generally problems should be detected and reported not quietly fixed. The way things are now you are restricted to a single DbContext per request as there is no way to enlist another DbContext to the same Connection and Transaction. An app built with multiple DbContexts is common and desirable. Thanks for your time.

**Comment by caleblloyd** [comment]
The default value for `UseAffectedRows` is `True` in MySqlConnector: https://mysql-net.github.io/MySqlConnector/connection-options/

We made that decision because that is the default in most MySQL drivers. The official C# driver is an exception, where it defaults to `false`, but we do not use the official driver.

I'll dig into this a little more today. I think we should:

1) check the connection string
2) try to change it if `UseAffectedRows=true` or `AllowUserVariables=false`
3) throw a verbose exception if changing it fails

**Comment by Kagamine** [comment]
Okay, then we should do the following things:

1. Suggest MySqlConnector set false as `UseAffectedRows` default value.
2. Refactory migrations to avoid use user variables.
3. If the DbConnection is not `UseAffectedRows=false;AllowUserVariables=true` then throw an exception to tell developers add `UseAffectedRows=false;AllowUserVariables=true` in his conn str.

**Comment by kampilan** [comment]
That sounds correct. To me anyway :) Thanks

**Comment by caleblloyd** [comment]
This will be like <1% of cases. Most people configure their DbContext with a connection string. Of the small amount that configure using connections, many pass unopened connections which can still be changed, much like we do today.

Forking or changing MySqlConnector for such a small change is overkill.

It'll be a real trivial PR, should take me 5 mins once I get to my computer. It will unblock @kampilan and will not break BC for any of our current users.

**Comment by Kagamine** [comment]
In PR #170, If the DbConnection is not UseAffectedRows=false;AllowUserVariables=true and it has been already opened, then throw an exception to tell developers add UseAffectedRows=false;AllowUserVariables=true in his conn str.

**Comment by caleblloyd** [comment]
In response to @kampilan 

> Generally problems should be detected and reported not quietly fixed.

This is subjective - there's a lot to be said for the happy path working out of the box.  If the first thing a user does is install this and start getting exceptions due to MySql's default values, it would be a headache.  The choice is pretty much already made for us - to maintain BC we must continue to correct the connection to what the library needs.  In PR #170, you will get a more verbose error message if you re-use the connection

> An app built with multiple DbContexts is common and desirable.

Yes, but re-using the same Connection between contexts is somewhat of an edge case.  Nobody has ever asked for it until now.  The only reason you would want to do this is if you must maintain a transaction across the contexts (like you've indicated you are trying to do).

MySql can only execute one query per connection at a time, and only have one open reader at a time.  We've done considerable work in [MySqlRelationalConnection](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlRelationalConnection.cs), [MySqlRelationalCommand](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlRelationalCommand.cs), and [SynchronizedMySqlDataReader](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/SynchronizedMySqlDataReader.cs) to ensure that queries are serialized properly.  This cannot be guaranteed if the connection is used outside of a single DbContext.

**Comment by caleblloyd** [comment]
Shipped in [1.1.1-prerelease-10009](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.1.1-prerelease-10009)

Please let us know how it works!

**Comment by kampilan** [comment]
As I am new to EF after years with Hibernate/NHibernate I will certainly defer to your judgement as to whether mine is an edge case or not. So injecting two DbContexts (with shared connection and transaction) into a controller and making calls on both during the course of the action on both is a bad idea? Sounds like that is what you are saying. The article I referenced seem to imply that this was an acceptable design pattern. Thanks for your input.

**Comment by caleblloyd** [comment]
I'd recommend using one DbContext per database if you can.  EF seems to push this pattern from what I've seen.

The `OnModelCreating` function can get out of hand when using the Fluent API on a lot of models.  One pattern that I use to manage this is to use a static "Meta" class for each model that uses the Fluent API.  I put that meta class right with the model so that it's all managed in the same place.  Example:

- [DbContext](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/AppDb.cs#L70-L72)
- [CRM Model](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Models/Crm.cs#L7-L47)
- [Generated Types Model](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Models/GeneratedTypes.cs#L10-L44)
- [People Model](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Models/People.cs#L7-L25)

**Comment by caleblloyd** [comment]
A couple more benefits I could think of:

- Inserts/Updates to the same DbContext when calling `SaveChanges()` or `SaveChangesAsync()` are [automatically wrapped in a transaction](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/854e79dca7d33b4c333972ed4a903822432071a6/src/Pomelo.EntityFrameworkCore.MySql/Update/Internal/MySqlBatchExecutor.cs#L59) if one has not already been started
- Eager Loading Queries trigger multiple queries in EF, and we [automatically wrap them in Repeatable Read transactions](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/854e79dca7d33b4c333972ed4a903822432071a6/src/Pomelo.EntityFrameworkCore.MySql/Query/Internal/MySqlAsyncQueryingEnumerable.cs#L46)

There's probably more benefits in EF Core as well...

**Comment by kampilan** [comment]
Got a chance to try this.
An exception was thrown in MySqlRelationConnection:

                if (!string.IsNullOrWhiteSpace(relationalOptions.ConnectionString))
                {
                    throw new InvalidOperationException(RelationalStrings.ConnectionAndConnectionString);
                }

It appears that setting the connection string on the option builder even though a live connection was supplied is the culprit:

            
            var extension = GetOrCreateExtension(optionsBuilder);
            extension.Connection = connection;
            extension.ConnectionString = csb.ConnectionString;
            ((IDbContextOptionsBuilderInfrastructure)optionsBuilder).AddOrUpdateExtension(extension);

            mySqlOptionsAction?.Invoke(new MySqlDbContextOptionsBuilder(optionsBuilder));

 Thanks
Jim
