### ISSUE TITLE
Could not load type 'MySql.Data.MySqlClient.MySqlConnection'

### ISSUE THREAD

**Issue by luis3199correia** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1707]
### Steps to reproduce
I'm using Pomelo.EntityFrameworkCore.MySql 3.1.1 and i'm getting this error
`Could not load type 'MySql.Data.MySqlClient.MySqlConnectionStringBuilder' from assembly 'MySqlConnector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92'.`

### The issue
When running the app this error appear
![image](https://user-images.githubusercontent.com/32116636/191805168-4e35d582-e4ea-47b9-8a90-e20c06d4560e.png)

### Further technical details

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version:
Microsoft.AspNetCore.App version:

Other details about my project setup:

I have two different app's using Pomelo.EntityFrameworkCore.MySql 3.1.1, one is working fine and I get this error in another app, where I'm using Orchard Core, and I get this error when I change Orchard Core version 1.0.0-rc2-15532 to 1.0.0-rc2-15852.

**Comment by bgrainger** [comment]
Pomelo.EntityFrameworkCore.MySql is not compatible with MySqlConnector >= 1.0, due to the breaking changes in that release: https://github.com/mysql-net/MySqlConnector/issues/824

Per https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.1.1#dependencies-body-tab it's compatible with MySqlConnector >= 0.61.0. Downgrade that package to 0.69.10.

You should probably also upgrade Pomelo to 3.2.7; see the table of version compatibility here: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#dependencies

**Comment by luis3199correia** [comment]
When upgrade to Pomelo 3.2.7 and MySqlConnector 0.69.10 I get this error `Version conflict detected for MySqlConnector. Install/reference MySqlConnector 1.1.0 `

**Comment by bgrainger** [comment]
Do you have some other package installed that depends on MySqlConnector?

Pomelo 3.2.7 clearly requires MySqlConnector >= 0.69.10 & < 1.0.0: https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.2.7#dependencies-body-tab

**Comment by luis3199correia** [comment]
No, I only need to install MySqlConnector when I upgrade Pomelo version to 3.2.7
