### ISSUE TITLE
CURRENT_TIMESTAMP not work with MySQL < 5.6

### ISSUE THREAD

**Issue by Kagamine** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#172]
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/3a8b8aa407bf78abd88b9025c60b97f45a8b83cd/src/Pomelo.EntityFrameworkCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs#L355

If MySQL < 5.6 should remove `()`

**Comment by caleblloyd** [comment]
This is not the issue.  The issue is that `DATETIME` cannot have DEFAULT or ON UPDATE `CURRENT_TIMESTAMP()` in MySQL < 5.6, only `TIMESTAMP` can.

To make matters worse, in MySql < 5.6 `there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause`.  [Reference](http://stackoverflow.com/a/267675/1419658)

So users cannot have both `Created` and `Updated` automatically in their fields.

I will fix this behavior but users must explicitly set their column type to `[Column(TypeName = "TIMESTAMP")]` on CLR Type `DateTime` to get auto-update timestamps.

@Kagamine should we throw an exception if a user tries to put DEFAULT or ON UPDATE on a `DateTime` in MySql < 5.6?

**Comment by Kagamine** [comment]
I think mysql will throw the exception

**Comment by Kagamine** [comment]
lgtm
