### ISSUE TITLE
Upgrade to 2.0.0-rtm

### ISSUE THREAD

**Issue by Kagamine** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#350]

**Comment by caleblloyd** [comment]
I am working on this, should be done by the end of the day

**Comment by caleblloyd** [comment]
EF 2.0.0-rtm won't work with .NET Core 2.0.0 Preview 2 SDK:

https://github.com/aspnet/EntityFramework/issues/9124

https://github.com/aspnet/EntityFramework/issues/9065

This probably means we need to wait for .NET Core 2.0 RTM, unless they plan on shipping a .NET Core 2.0 preview3.  Our tests won't work otherwise.  And migration and scaffolding won't work for our users.

I fixed all of the changes introduced by 2.0.0-rtm so I'll open the PR, but it will fail tests until we can get a newer version of .NET core 2.0

**Comment by Kagamine** [comment]
Create a dev branch forst, and I will get the sdk from .net team

**Comment by caleblloyd** [comment]
I don't think it's worth the effort.  We can't publish a prerelease because our users aren't going to install nightly builds to test it.  It'd be too confusing for everyone.

The issue only affects EF tooling, so Migrations and Scaffolding.  I got the project to build with EF 2.0.0-rtm, it just won't run EF Migrations/Scaffolding without a nightly SDK right now.
