### ISSUE TITLE
Default Timestamps

### ISSUE THREAD

**Issue by sanishx** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#361]
Im trying to set up a model so that when a new one is created the column CreatedAt is set to the current timestamp and when a row is updated the UpdatedAt is set to the current timestamp. I'm using codefirst migrations.

I have these annotations on the fields i'm using

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]        
        public DateTimeOffset CreatedAt {get; set;}

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]        
        public DateTimeOffset UpdatedAt {get; set;}

But when I insert I get a mysql error Field  doesn't have a default value for CreatedAt. 

Also Ideally I want a TIMESTAMP column instead of datetime, is this possible?

### Further technical details

MySQL version: 5.7.18
Operating system: ubuntu 16.04
Pomelo.EntityFrameworkCore.MySql version:2.0.0-rtm-10056

**Comment by caleblloyd** [comment]
This has been fixed in [2.0.0-rtm-10059](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.0.0-rtm-10059)

Yes you can use a timestamp column see this example: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/d8ca9b1a7def8030daaf52abd5742158af53a77b/test/EFCore.MySql.FunctionalTests/Models/GeneratedTypes.cs#L107-L113
