### ISSUE TITLE
Database failover support

### ISSUE THREAD

**Issue by mguinness** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#441]
How would the Pomelo provider function during a failover scenario?  After a primary gets switched to a replica the IP address in DNS will change.  Would that change be effective immediately or would latency be expected?

I'm guessing that the connection is cached for performance issues, either in the provider or the underlying MySqlConnector library.  I assume that DbContext pooling in EF Core should be avoided also.  Do the recent changes for connection resiliency help with this?

Would the connection be renewed only after a connection fails, or would the DNS change be somehow detected and connection re-established?  Due to the Provider/ADO/EF interrelationships it's hard to understand, so any background would be appreciated.

/cc @caleblloyd @bgrainger

**Comment by yukozh** [comment]
I think this thing should be done in a proxy layer, the proxy have to detect the server down and forward all packages into a replica server.

**Comment by bgrainger** [comment]
I can speak to the connection pooling logic in MySqlConnector.

When `MySqlConnection.Open` is called, an existing connection will be retrieved from the pool. If `ConnectionReset=True` (the default), then a connection reset packet will be sent. Otherwise, a ping packet will be sent (to check server liveness). I assume that an IOException or SocketException would be thrown at this point. If so, the connection will be marked as failed and a new one will start being created. (If there was no pooled connection, we'll skip this whole paragraph and go straight to creating a new connection.)

The connector will invoke the .NET API to resolve the host name to IP address(es). I don't know the details, but I imagine there could be multiple levels of caching (in the OS and .NET) unless the record has an extremely short TTL. 

If we get a stale A record, then connecting to that IP will fail and that exception will ultimately be propagated as a `MySqlException`. (There would be more steps if a) the host name resolves to multiple IP addresses, or b) the connection string includes multiple comma-delimited host names.)

If we get an updated A record, then it should "just work". But that feels like a lot of "if"s to make that work reliably in practice.

**Comment by bgrainger** [comment]
> I think this thing should be done in a proxy layer, the proxy have to detect the server down and forward all packages into a replica server.

I assume the proxy would have to close all open connections because it can't seamlessly transfer them (with all active session state) to the new backend. So most of the steps in my description above would still be relevant (i.e., a pooled connection failing when being reset); the only difference is the host name would always keep resolving to the same (i.e., proxy) IP address.

**Comment by mguinness** [comment]
Thanks for the answers.  I didn't know that you could specify multiple hosts in the connection string.

Whilst doing some research I discovered [MySQL Router](https://github.com/mysql/mysql-router) which could be a solution as a proxy.
