### ISSUE TITLE
Upgrade from 1.1.2 to 2.x Generates Sql Without Auto-Increment

### ISSUE THREAD

**Issue by mpereira05** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#455]
### Steps to reproduce
* Create a new .Net Core 1.1 project
* Install Pomelo.EntityFrameworkCore.MySql version 1.1.2
* (Optional) Install Microsoft.EntityFrameworkCore.Tools
* Create a sample class such as the following
```
public class TestClass
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```
* Create a simple ApplicationDbContext such as the following
```
public class ApplicationDbContext : DbContext
    {
        public DbSet<TestClass> TestClasses { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseMySql("YourConnectionStringHere");
        }
    }
```
* In a console, run `add-migration TestMigration1`
* Upgrade Project to .Net Core 2.0
* Upgrade Pomelo.EntityFrameworkCore.MySql to version 2.0.1
* In the console, run `add-migration TestMigration2`
* In the console, run `script-migration -from TestMigration1 -to TestMigration2`
** You'll have to update the Migration names to include the timestamp generated

### The issue
In the SQL script generated by the second migration (TestMigration2) after upgrading to version 2.0.1 of this library, the AUTO_INCREMENT for the column Id is not generated.

If you make a clean project with version 2.0.1 to start, it adds AUTO_INCREMENT properly.  This appears to only happen in the migration you make after upgrading Pomelo.EntityFrameworkCore.MySql from version 1.1.2 to 2.0.1.

### Further technical details
MySQL version: 5.7.19
Operating system: Windows 10 Enterprise Version 1703 Build 15063.674
Pomelo.EntityFrameworkCore.MySql version: 1.1.2 -> 2.0.1

Other details about my project setup:
N/A

**Comment by caleblloyd** [comment]
We have a [test for Legacy Migrations](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/EFCore.MySql.FunctionalTests/scripts/legacy.sh) and CI runs our old 1.1.2 migrations with new migrations in order to ensure that they are backwards compatible

I don't think there's much more we can look into.  If it's a use-case specific error, try manually editing your migration.   If it's a bigger issue that you think comes from the codebase in general, please try to provide a full recreate in a Git repo, or submit a PR if you're able to find the root cause.  Thanks.

**Comment by mpereira05** [comment]
I ended up manually editing my migration for now to add the AUTO_INCREMENT back to the SQL.

In case you're interested in the full recreate, I uploaded a project affected by this at:
https://github.com/mpereira05/PomeloUpdateBug
