### ISSUE TITLE
Pomelo.EntityFrameworkCore.MySql 1.0.1 milestone

### ISSUE THREAD

**Issue by Kagamine** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#47]
### Using Microsoft.EntityFrameworkCore.Relational 1.0.1

Microsoft has released Microsoft.EntityFrameworkCore.Relational 1.0.1. We have switched the version to 1.0.1 now. This has been included in [`1.0.1-prerelease-10002`](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.0.1-prerelease-10002)

### Scraped Pomelo.Data.MySql

In the past [Pomelo.Data.MySql](https://github.com/PomeloFoundation/Pomelo.Data.MySql) was forked from the official https://github.com/mysql/mysql-connector-net, it doesn't support async operations, and the forked version is not a real MIT licensed library. Pomelo.MySql.Data, is mostly a rip of the Oracle version and is likely in violation of their license. 

So, we have switched to [bgrainger/MySqlConnector](https://github.com/bgrainger/MySqlConnector), the MySqlConnector is friendly to __async__. Besides, the MySqlConnector is under the real MIT license.

Thanks for contributions of @caleblloyd @bgrainger 

These features were included in [`1.0.1-prerelease-10001`](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.0.1-prerelease-10001).

### Json supporting

We are still working on the Json queries. The Linq expressions which point to JsonObject<T> will be analyzed into native sql expressions.

```
DB.Blogs.Where(x => x.Tags.Object.Contains("MySQL")).ToList();
```

to

```
SELECT * FROM `Blogs` WHERE JSON_CONTAINS(`Tags`, '"MySQL"');
```

### Enum supporting

In the current version, enum fields has been stored as a int column. We have received the suggestion #36. So, in this milestone, we plan to support the native mysql enum field type.

**Comment by caleblloyd** [comment]
`JSON_CONTAINS` in MySQL causes a full table scan.  If the table is large, this query will be very slow.  MySQL's recommended approach is to create "Generated Virtual Columns"

- [MySQL Documentation for Generated Virtual Columns](https://dev.mysql.com/doc/refman/5.7/en/create-table-secondary-indexes-virtual-columns.html)
- [Good Article on Generated Virtual Columns](http://mysqlserverteam.com/indexing-json-documents-via-virtual-columns/)

I don't know if we should expose `JSON_CONTAINS` queries through LINQ.  People may use them thinking that it's a good idea, when in reality once their table grows they will have very slow queries.

@Kagamine what are your thoughts?  Should we nix `JSON_CONTAINS` for 1.1 and instead find a way to let people query Generated Virtual Columns?

**Comment by Kagamine** [comment]
Wow, interesting. It seems the GVC is better.

**Comment by dNetGuru** [comment]
&lt;rant&gt;
I personally think a JSON column type is not a great idea since it has a huge potential for being misused by the developer.

Think about it, any table can be stored in the following table by serializing the object representing the columns in the ```data``` column:
```sql
CREATE TABLE DataStore (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`data` JSON NULL
)```

Now should we do this? Absolutely not! MySQL is not a document store and if the developer thinks they need something like this then a document database is what they need to look for!

I always suggest using the JSON column type as you would a TEXT column type that has CSVs in it OR as you would a BLOB! Never store data that you need to search through or select a subset of in it.

Sure the possibility in index JSON columns by extracting their values is good to have for interop and backwards compatibility (e.g when you have some data in JSON format that you need to import and use) but otherwise I'd say skipping GVCs and going through the motions of defining a column for it would be a better idea!

Also note that GVCs are not an option in the most common use cases of these BLOB types like JSON anyways. Just like the one you have in the README file (the tags list).

**Comment by caleblloyd** [comment]
@dNetGuru the `JSON` type is very useful.  If for no other reason, the JSON is stored in an [Optomized Format](https://dev.mysql.com/doc/refman/5.7/en/json.html)

> I always suggest using the JSON column type as you would a TEXT column

That is a good suggestion.  It should never be searched directly, as this will cause a full table scan.

> skipping GVCs and going through the motions of defining a column for it would be a better idea since it will be faster and will not impose a read/write overhead

GVCs can be VIRTUAL or STORED.

VIRTUAL indexed columns will write to the index when created/updated, but will not write to storage.  Since the JSON format is optimized, generating the value when a row is returned in a result set will be very fast.  This also allows to cut down on storage space.

STORED indexed columns will write to the index and storage when created/updated.  There's really no difference here - the data is just extracted to the secondary column on the DBMS instead of on the App Server.  I'd go so far as to argue that the DBMS will do this faster because it's a highly optimized codepath.

**Comment by caleblloyd** [comment]
GVCs work just fine in our library with no changes!  I've committed an [example model](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Models/GeneratedTypes.cs) and [test](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Tests/Models/GeneratedTypesTest.cs) in #86

**Comment by caleblloyd** [comment]
Congratulations to all of the contributors who worked on 1.0.1 and all of the testers who opened issues against 1.0.1! It's a great step forward and provides a very powerful tool to the modern .NET stack. I'm looking forward to using this in my apps and continuing to improve the library in 1.1.0!
