### ISSUE TITLE
Make a benchmarks

### ISSUE THREAD

**Issue by Kagamine** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#49]
Compare to Pomelo.EntityFrameworkCore.MySql-1.0.0(rtm), Pomelo.EntityFrameworkCore.MySql-1.0.1(prerelease), MySql.Data.EntityFrameworkCore(7.0.5)

**Comment by caleblloyd** [comment]
Performance tests in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/54 can benchmark all of these.

I've already provided an environment variable to test with the Oracle Provider.  But MySql.Data.EntityFrameworkCore(7.0.5) has so many bugs that it doesn't work at all.

To run functional or performance tests with Oracle provider, set environment variable `EF_PROVIDER = "oracle"`

To test Pomelo.EntityFrameworkCore.MySql-1.0.0(rtm), you can switch the Pomelo package source to [caleblloyd-Pomelo.EntityFrameworkCore.MySql/1.0.0-prerelease-20160805](https://www.nuget.org/packages/caleblloyd-Pomelo.EntityFrameworkCore.MySql/1.0.0-prerelease-20160805).  I had to make a copy of the NuGet package under a different name in order to load it within the project.
