### ISSUE TITLE
deserialization jsonObject type longer time

### ISSUE THREAD

**Issue by huxiany** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#602]
Querying the database, processing JsonObject type of deserialization time is too long, resulting in poor performance. 
https://github.com/huxiany/EFCoreIssue

![efcore](https://user-images.githubusercontent.com/28701403/41225619-c84ed0c4-6da1-11e8-9c28-794db4800005.png)

**Comment by mguinness** [comment]
This appears to be a usage issue, in your normal query (getTiles) you aren't filtering (you need to add a where clause).

**Comment by LiangZugeng** [comment]
Thanks for the reply, actually the filter isn't the issue here, the initialization code created 7000 lines of records in the DB and all of them have the same SalesOrderID (578) so it doesn't matter if a where clause is used or not.

The performance bottleneck is at the deserialization of string content of JsonObject, we tested the performance of the two SQL queries (with MaterialSpec or MaterialSpec as null), MySQL returned the dataset to EF Core with almost identical time, and with MaterialSpec it took 50x to 100x time to process the result.

Please kindly reopen the issue and investigate it further, we tried to look into the Polemo.EFCore.MySql source code but we are new to EF Core internal design so we had no much progress pinpointing the root cause.

**Comment by mguinness** [comment]
I suggest you file an issue in the underlying library at [Pomelo.JsonObject](https://github.com/PomeloFoundation/Pomelo.JsonObject).

**Comment by caleblloyd** [comment]
@LiangZugeng if you need performance-critical code you should probably just retrieve as a `string` and write a method to deserialize the field on-demand

Pomelo will Convert any `JsonObject<T>` using reflection when it is read from the database.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/4c099402e3c044fe0cc0d876d8e73630f2eb36c6/src/EFCore.MySql/Storage/Internal/WrappedMySqlDataReader.cs#L96-L111

**Comment by LiangZugeng** [comment]
@caleblloyd thanks for the information.

We spent some time doing the perf profiling and found that the function you mentioned is exactly where the performance issue is, every time a JsonObject needs to be parsed from a string, ConvertWithReflection<T> is called, and every time it constructs the type conversion lambda expression from scratch (including the generation and compilation), this caused a very bad performance.

I submitted a PR #606 with our fix, please review it. Let me know if this PR should go into the master branch instead of 2.0.1-rtm (that way a backport may be needed to 2.0.1).

@mguinness we did find some code in Pomelo.JsonObject impacting the deserialization performance, but it's a minor issue (4% to 8% performance gain after applying a fix) so we didn't include the fix in our PR, I will file a new issue in that repo to discuss the fix, when everything is talked and agreed we will then submit a PR.

**Comment by caleblloyd** [comment]
Fixed in [https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.1.0-rc2-final](2.1.0-rc2-final)
