### ISSUE TITLE
Strong name Pomelo.EntityFrameworkCore.MySql.dll

### ISSUE THREAD

**Issue by dougbu** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#603]
### Steps to reproduce
With a recent .NET Core SDK, build or run a project that depends on the Pomelo.EntityFrameworkCore.MySql. package.

### The issue
Building such a project and targeting .NET Core results in the following warning:
```
CSC : warning CS8002: Referenced assembly 'Pomelo.EntityFrameworkCore.MySql, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [Project.csproj]
```
This warning is of course treated as an error if `$(WarningsAsErrors)` is `true` -- which is fairly common. In other words, the lack of a strong name can often fail builds.

If that project also targets .NET Framework (which EF Core supports), you'll hit a runtime failure:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Pomelo.EntityFrameworkCore.MySql, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

In essence I'm suggesting applying mysql-net/MySqlConnector#224 to this repo given ASP.NET Core packages can be used in "full framework" .NET Framework projects and given the recent warnings about strong naming. In addition, Microsoft now recommends strong naming; see https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies for example.

By the way, mysql-net/MySqlConnector#224 has been fixed and MySqlConnector.dll is now strong named.

### Further technical details
(Only the Pomelo.EntityFrameworkCore.MySql package version should be relevant in this issue.)

MySQL version:
- 5.7.19 I believe (based on the name of the Docker image we're using)

Operating system:
- Windows 10 version 1803 (OS Build 17134,48)

Pomelo.EntityFrameworkCore.MySql version:
- 2.1.0-rc1-final

**Comment by caleblloyd** [comment]
We can take this as a contribution

**Comment by andresrsanchez** [comment]
Hi guys, i'm probably wrong but this issue is solved with these techniques: [https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name](url) or not? Too simple for anyone to have done it i think!

Thanks for all!!

**Comment by mguinness** [comment]
@yukozh The larger question is should we share a strong-name private key for all projects in Pomelo Foundation, i.e. [JsonObject](https://github.com/PomeloFoundation/Pomelo.JsonObject/issues/8).

**Comment by yukozh** [comment]
I don't have any private key. Feel free to create one and share it to project owners.

**Comment by lauxjpn** [comment]
I agree that we should strong name sign all assemblies, so that people who need to strongly name their own assemblies can use Pomelo assemblies without problems.

There is no need to reuse the same strong name key for every Pomelo assembly/project, because this does not provide any benefits. I suggest we just create `.snk` files on a solution/project level, as this will be easier to manage.

We should also add the `.snk` files to their respective repositories (they include the private keys), so people can recompile their custom version of the assemblies for their own projects and replace the official version without any hassle.
This is not a security concern, because strong named assemblies are not a security concept but an identity concept.

See the EF Core guidelines about [Strong Name Signing](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md) for further details.

**Comment by yukozh** [comment]
@divega, There is an unofficial package on NuGet gallery: https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql.Signed/ 
We have already submitted the taken down request, however received no response.

**Comment by lauxjpn** [comment]
@yukozh Are there any issues with the package? Isn't that allowed by the MIT license?
It might be a more effective approach to just ensure that we have strong named assemblies for `2.2.6` and `3.0.0` ready, so users don't feel the need to turn to other packages in the first place. What do you think?

**Comment by yukozh** [comment]
It is allowed, but they should not use the same name as `Pomelo`, it will cause people misunderstanding. Because that is not release by us.

**Comment by lauxjpn** [comment]
Ah, I see. Have we tried getting in contact with [arodriguez](https://www.nuget.org/profiles/arodriguez) via the [Contact Owners](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql.Signed/2.1.0/ContactOwners) link? If we provide a strong named package, the owner is probably happy to take down his/her package.

What's your opinion about how far back we need to strongly name our assemblies? Is 2.2.6 enough or do we need to rerelease 2.1.4 as well to make the unofficial package obsolete?

**Comment by andresrsanchez** [comment]
Yeah it's me and i totally forgot about it, i'll try to login and "remove" the package.

**Comment by lauxjpn** [comment]
@andresrsanchez Awesome! Thank you for the quick response and for helping the community with a signed package as a workaround in the meantime!

I will prepare signed versions of `Pomely.EntityFrameworkCore.MySQL` later today.

@caleblloyd, @yukozh, @bgrainger: Does anybody have the official/original Pomelo logo/icon and can either upload it to NuGet or provide it to me and make me part of the NuGet gang?

**Comment by yukozh** [comment]
https://avatars0.githubusercontent.com/u/19828814?s=200&v=4 i

**Comment by lauxjpn** [comment]
@yukozh Thanks! I just created a NuGet account under the name of `LauXjpn`.

**Comment by yukozh** [comment]
![image](https://user-images.githubusercontent.com/2216750/69137589-04fbcf00-0af8-11ea-9275-72fde4b24acf.png)

**Comment by yukozh** [comment]
And I am not sure create `Pomelo.EntityFrameworkCore.MySQL` is allowed, because the case of the letters is the only diff between unsigned one. If that is disallowed, I suggest `Pomelo.EntityFrameworkCore.MySql.StrongName`.

**Comment by lauxjpn** [comment]
I would just strongly name our main package assemblies because this is recommended for all public .NET packages anyway.

See [Strong Name Signing](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md) and [Create strong named .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries) (the latter directly addresses open source libraries).

@caleblloyd We should check on how Arcade deals with the following:

>✔️ CONSIDER incrementing the assembly version on only major version changes to help users reduce binding redirects, and how often they're updated.
>
>Read more about [versioning and the assembly version](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/versioning#assembly-version).

**Comment by mguinness** [comment]
I'm not very familiar with [GitHub Packages](https://github.com/features/packages), but could we host the NuGet package there instead?

**Comment by bgrainger** [comment]
GitHub Packages can be useful for hosting nightly/CI builds, but it's not useful as a general distribution point, because all downloads require authentication (i.e., a GitHub account) and a separate feed to be added to users' `nuget.config` files.

For distributing GA releases, nuget.org is still much better.

**Comment by mguinness** [comment]
Ah I see, thanks for the explanation.  So I guess it could be used in place of MyGet or Azure Artifacts.

**Comment by lauxjpn** [comment]
If there are no objections, I will merge and publish a `2.2.1` release for the (from now on strongly named) `Pomelo.JsonObject` assembly shortly, so we can reference it from strongly named releases of `Pomelo.EntityFrameworkCore.MySql` from now on.

**Comment by ajcvickers** [comment]
@roji What did you do about strong naming for Npgsql?

**Comment by roji** [comment]
Npgsql is strong-named, just so that other strong-named assemblies can depend on it - I don't think there's any drawback in doing this (assuming all your dependencies are already strong-named).

I also agree with @bgrainger above - the general distribution point for .NET packages should remain nuget.org. For nightly/CI, we've also looked at Github Package Registry for nightly/CI package distribution and are remaining with Myget for now, since GPR is quite new and still lacking some important features (e.g. automatic package retention rules).

**Comment by lauxjpn** [comment]
@yukozh I created a release for `Pomelo.JsonObject` version `2.2.1` on GitHub, but couldn't find any publishing procedure for NuGet in the yaml scripts. Is this a manual process?

**Comment by lauxjpn** [comment]
@yukozh & @caleblloyd If you make me an owner of the Pomelo.JsonObject package on NuGet I will upload the `2.2.1` release manually.

**Comment by caleblloyd** [comment]
@lauxjpn Pomelo.JsonObject is still on MyGet

https://www.myget.org/feed/pomelo/package/nuget/Pomelo.JsonObject/2.2.1

I just invited you, there is a "Push" button when logged into MyGet that will transfer it over to NuGet

![image](https://user-images.githubusercontent.com/2414837/69404269-ed962f00-0d0d-11ea-886d-66f1eb1634a7.png)

Also added you and @bgrainger as managers of the package on NuGet

**Comment by bgrainger** [comment]
Yes, I think it makes sense to have all "Pomelo" assemblies strong-named with the same key.
