### ISSUE TITLE
First Pomelo 2.1.x RTM release will be 2.1.1

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#630]
Pomelo [2.1.0-rc2-final](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.1.0-rc2-final) is out.  Since EF Upstream is already on version [2.1.1](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/2.1.1) and this RC uses this upstream version, we are going to increment the patch version number to match EF Upstream and publish `2.1.1`.

Target to publish Pomelo 2.1.1 RTM is by the end of the weekend, provided there are no major issues found in `2.1.0-rc2-final`.

**Comment by ajcvickers** [comment]
@caleblloyd Thanks for publishing this. Is there currently anything blocking an RTM, assuming no major issues from the RC2 release?
/cc @AndriySvyryd @divega

**Comment by mguinness** [comment]
I don't believe these are blocking, but there were some issues at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/552 identified by maumar.

**Comment by caleblloyd** [comment]
Correct, no issues blocking RTM!

**Comment by WillooWisp** [comment]
I just reported this issue, that might be blocking, #631 

The workaround is to check the ActiveProvider and conditionally leave out the filter part if not SQL Server, but that is not so nice in the long run.

**Comment by ajcvickers** [comment]
In my opinion, #631 should not be blocking. In fact, I think that provider conditional code in the migration sounds more like the correct thing to do than to have MySQL just ignore the filter. Any thoughts @bricelam, @divega, @AndriySvyryd?

**Comment by AndriySvyryd** [comment]
I don't think this is blocking. But since it's unlikely that filters will be ever supported than ignoring it seems ok, just to prevent the regression.

**Comment by WillooWisp** [comment]
I agree that it might not be blocking, since there are workarounds, but to me it feels very obvious that the provider should handle the generated code for the model builder. I mean the whole point of using EF is to be database agnostic as far as possible. It should be up to each provider to correctly handle as much as possible, e.g. for example if filters should become supported in MySQL 8+, or something, or in MariaDB the correct SQL syntax should be generated taking advantage of this, if targeting a specific version, vs what is being generated for older versions. Just my opinion...

**Comment by caleblloyd** [comment]
Index Filters ignored in #637 
A huge memory consumption issue was found in #633 and fixed in #638 

Last call for blocking issues, would like to publish 2.1.1 RTM tomorrow.

**Comment by caleblloyd** [comment]
[2.1.1](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.1.1) is published!
