### ISSUE TITLE
Connection is not closed even if the program exited

### ISSUE THREAD

**Issue by shwuhk** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#664]
I am using MariaDB and the connection string is `optionsBuilder.UseMySql("server=1.1.1.1;port=3306;user=user;password=password;database=dbName;TreatTinyAsBoolean=false");`
and try with the following code.
```
static async Task Main(string[] args)
{
  using (var dbContext = new MyDbContext()) {
    var d = await dbContext.MyEntity.FindAsync("id");
  }
}
```
After the program exit, I find that there is some sleeping connection in the database and it will exist for around ten minutes. This will end up using all of our connections.
Is it a bug of by design or I should do anything else to clean up all the connections?

**Comment by mguinness** [comment]
Closing since this isn't relevant to this provider.  See [EF Core MySql connections not closing](https://stackoverflow.com/questions/44538321/ef-core-mysql-connections-not-closing) and try using `Pooling=false` in your connection string.  If this doesn't work look into [MySqlConnector](https://github.com/mysql-net/MySqlConnector) which is the underlying library that this provider uses.

**Comment by shwuhk** [comment]
I will ask in that library then. Thanks for your help.

**Comment by shwuhk** [comment]
@mguinness 
I found that I can solve this problem if I call `MySql.Data.MySqlClient.MySqlConnection.ClearAllPools()` when my program exit but I don't think this should be called by user. Do you have any ideas? I don't think this should be related to [MySqlConnector](https://github.com/mysql-net/MySqlConnector) but should be related to EF(?) or Pomelo.EntityFrameworkCore.MySql(?)?
