### ISSUE TITLE
MySqlException: Unknown charset 'maccecsas'

### ISSUE THREAD

**Issue by LanceFang** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#682]
I added character set Settings to the connection string and it still doesn't work
![image](https://user-images.githubusercontent.com/13814982/45407129-18f9a480-b69b-11e8-8692-c8ba8a908324.png)

**Comment by mguinness** [comment]
Please use the new issue template when creating an issue.  It's not clear to me what your problem is, does MariaDB have charset maccecsas (Mac Central European - Case Sensitive, Accent Sensitive) defined?  Closing issue and will re-open if more specific information is provided.  Try Stack Overflow for help with general MySQL/MariaDB help.
