### ISSUE TITLE
MYSQL 5.7 GTID

### ISSUE THREAD

**Issue by yuyixg** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#746]
Error
MySqlException: Statement violates GTID consistency: CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can only be executed outside transactional context.  These statements are also not allowed in a function or trigger because functions and triggers are also considered to be multi-statement transactions
### 
DbContext.SaveChanges()

**Comment by mguinness** [comment]
Closing since new issue template wasn't used, but can reopen if more detail is provided.

However it appears that you have encountered [Restrictions on Replication with GTIDs](https://dev.mysql.com/doc/refman/5.7/en/replication-gtids-restrictions.html).

**Comment by yrfu** [comment]
Dear developers,

This restriction is should be resolved in MySQL 8.0 whose version of the documentation section on [Restrictions on Replication with GTID](https://dev.mysql.com/doc/refman/8.0/en/replication-gtids-restrictions.html). The documentation above linked was for 5.7. Even 5.6, when GTID was first introduced had this restriction. 

The issue on CREATE/DROP TEMPORARY TABLE in 8.0.13 onwards read differently which I paste its screenshot below:

<img width="1243" height="163" alt="Image" src="https://github.com/user-attachments/assets/5e3be3e1-6f15-4ab6-9c0a-4c5ed4a5d42d" />

Some sites and blogs attest that issue is largely resolved as per the documentation screenshot:
https://blog.s-style.co.jp/2019/11/5440/
https://opensource.actionsky.com/20220713-mysql8-0/
https://cloud.tencent.com/developer/article/2048022
