### ISSUE TITLE
I get bool always as true when column type is bit(1)

### ISSUE THREAD

**Issue by papmodern** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#760]
### Steps to reproduce
It is completely random!!!!!! in some tables or some situations it works fine.
I think it appears mostly when I have Include and ThenInclude in my queries 

### The issue
In code first migration, I create some bool props, I can create and update the values successfully. But when I tend to read some boolean that are zero in db, ef core returns them as true :-|
The interesting part is that by changing the type of column to tinyint(1) everything works correctly.
So I had to add annotation above all of my bool types to insure all bool columns are tinyint and nothing goes wrong anywhere.

This issue happens just when there is more than one row.

### Further technical details

MySQL version: 5.7.23
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.1.4
Microsoft.AspNetCore.App version: netcoreapp2.1

**Comment by mguinness** [comment]
The info that you provided is not enough to repro.  If you can provide a sample project that exhibits the problem you specified (even if it's random) then we can take a look to see where this issue is occurring.

**Comment by xenji** [comment]
`tinyint(1)` is a nerve-wrecking special case in MySQL. EF behaves according to the MySQL documentation where `boolean` and `tinyint(1)` are synonyms [[ref](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-overview.html)]. The .net driver provides a configuration property to change the interpretation of `tinyint(1)` named `TreatTinyAsBoolean` [[ref](https://dev.mysql.com/doc/connector-net/en/connector-net-8-0-connection-options.html)]. (Due to limitation on the MySQL page, I cannot link directly to the paragraph.)

I must admit, that I do not know if and how it would be possible to change the behaviour here.

**Comment by mguinness** [comment]
See [Add TreatTinyAsBoolean connection string option](https://github.com/mysql-net/MySqlConnector/issues/141) for discussion on `TreatTinyAsBoolean` option.
