### ISSUE TITLE
Store only date portion of DateTime value

### ISSUE THREAD

**Issue by smr-mohammadzadeh** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#767]
### Steps to reproduce

I am trying to store date in MySql database with "0000-00-00" format as MySql "Date" data type. so I added this field to my entity model:
`[Required]
 [Column(TypeName = "date")]
 public DateTime Date { get; set; }`

### The issue

But when I create a new row with EF Core DbContext, the stored value format is i.e. 2019-03-27T00:00:00. how can I store the only date portion in the database?

### Further technical details

MySQL version: 8.0
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.2.0
Microsoft.AspNetCore.App version: 2.2

**Comment by smr-mohammadzadeh** [comment]
sorry for my mistake. the date value is storing as the desired format in the database, but it seems when I trying to make a query and save "date" column value in the DateTime variable, it will be converted. i.e. 2019-03-27 will be converted to 2019-03-27T00:00:00. so now I know what should do to convert it.

**Comment by fdsouza1976** [comment]
@smr-mohammadzadeh good morning!
I also have the same problem.
Can you write down the solution you got?
Thank you in advance!

**Comment by lauxjpn** [comment]
@fdsouza1976 I am not sure I understand, what the actual issue is. If you use the `date` MySQL data type for a column, then the column will only store the date.
Since .NET does not have a data type that only stores the date part, the `date` column will be represented by `System.DateTime` in .NET (with a time of `00.00.00`).
Please elaborate, where the problem lies with the current approach, and what you would expect instead (or post some code to talk about).
