### ISSUE TITLE
Character Set Introducers for Unicode Strings

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#834]
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/ed38395f7416ff702a1ca960200fbfe106a5b03c/src/EFCore.MySql/Storage/Internal/MySqlStringTypeMapping.cs#L91-L104

Would a [Character Set Introducer](https://dev.mysql.com/doc/refman/8.0/en/charset-introducer.html) like `_utf8mb4` suffice for this usage?

**Comment by bgrainger** [comment]
`U&"..."` and `_utf8mb4` address two different concerns:

* The former allows Unicode characters to be specified in a string literal using the escape sequence `\nnnn` or `\+nnnnnn`.
* The latter specifies the character set of the bytes comprising the string that follows the introducer. This is redundant (and not actually possible to use) with MySqlConnector, since all .NET strings are Unicode and MySqlConnector always uses UTF-8 (`utf8mb4`) to encode strings on the wire. It only makes sense to use when you can control the character set that's used on the wire (and MySqlConnector doesn't permit this).

I don't understand the comment in the Pomelo source code. Again, since .NET is fully Unicode, and MySQL can understand Unicode characters that are encoded as UTF-8 byte strings, there's never a need to escape Unicode strings.

I'm guessing the `IsUnicode` property is there to handle databases that make a hard differentiation between ANSI (`VARCHAR`) and Unicode (`NVARCHAR`) strings? IMO, there's no need to handle that property at all in Pomelo; just output the same string literal in both cases and let MySqlConnector encode it.

**Comment by lauxjpn** [comment]
@bgrainger Thanks for clarifying that!
