### ISSUE TITLE
Ability to specify engine, charset, ROW_FORMAT and more

### ISSUE THREAD

**Issue by mylemans** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#84]
Would it be possible to add a method to specify a custom CHARSET, ENGINE, ROW_FORMAT (and more?) when creating tables?

Or is that already possible at the moment?

I'd like to use what was stated here: http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/

**Comment by caleblloyd** [comment]
Right now the only way to achieve that is to hand-build a migration that calls ALTER TABLE.

I will look into adding an argument to `MigrationBuilder.CreateTable` that would allow for this.

**Comment by caleblloyd** [comment]
@mylemans as a side note, PKs that big are generally a design problem.  InnoDB stores the PK along with every secondary index, and having a PK that big is going to cause the database to grow very large.

If PKs are getting that big, you should consider hashing all of the unique data for the PK, and storing the unhashed data separately in a non-indexed fields, such as TEXT

**Comment by mylemans** [comment]
I'm aware of that solution, and I'll be using it as part of the final solution, but I'd still like to specify these values at creation time.

**Comment by Kagamine** [comment]
Maybe need extend a fluent api .IsCharset("") and CharsetAttribute [Charset("")]

**Comment by caleblloyd** [comment]
I think we should probably try to extend [TableMapping](http://ef.readthedocs.io/en/latest/modeling/relational/tables.html)

    Attribute:
    [Table("blogs", Schema = "blogging", Extra="ENGINE=InnoDB DEFAULT CHARSET=latin1")]
    
    Fluent API:
    modelBuilder.Entity<Blog>()
        .ToTable("blogs", schema: "blogging", extra: "ENGINE=InnoDB DEFAULT CHARSET=latin1");

**Comment by Kagamine** [comment]
MySQL supports specify column charset.

**Comment by caleblloyd** [comment]
ColumnAttribute uses TypeName for type, char set, and collation:

    [Column(TypeName = "VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci")]

TableAttribute unfortunately has nothing like this presently.  We would have to add it in the form of the `extra` property proposed above

**Comment by Kagamine** [comment]
Can we open an issue in .netfx or corefx to ask them add a field?

**Comment by jemiller0** [comment]
I'm running into the same problem as mylemans. I have an existing database that has a lot of concatenated keys that I'm reverse engineering and then recreating in using EF Core. Personally, I can't stand this and always simply use identity columns for primary keys on databases I design myself, but, it's a legacy database that I have no control over. I also have a requirement to support the full set of UTF-8. So, I'm using utf8mb4. One of the tables that is failing has a varchar(255) in it's primary key. This fails due to the index length restriction of 767. I think each character may take 3 or 4 bytes in the index which puts it over the limit. So, it's not that hard to go over the limit. I'm able to work around this with MySQL by setting defaults. However, I'm also trying to get it to work with MariaDB. MariaDB defaults to using Antelope file format and as far as I know  you can't set Barracuda as a default because according to the documentation, certain system tables are incompatible with it. So, as far as I know, I would need to be able to specify the file format explicitly for each table. I was hoping there would be a fluent API method along the lines of .ForMysql*() that might let me specify additional text to be added to the CREATE TABLE statement. Personally, I think I would prefer a fluent API way of doing it over an attribute. I don't want to put DBMS-specific info into attributes. I would rather use the .ForX*() convention and the fluent API that Microsoft and PostgreSQL seem to be using.

A different unrelated problem I ran into is that the Pomelo provider was mapping C# decimal fields to SQL DECIMAL with maximum precision and scale which looked like it was huge. I think it would be better to default to more reasonable values, like the SQL Server provider does.

Other than these few issues, I've been happily using the Pomelo provider for the past few months and it's been working great. I'd like to give a big thanks to the Pomelo developers. You're doing a much better job than Oracle is. I can't even get their driver to work at all on the full .NET Framework.

**Comment by jemiller0** [comment]
Or, ideally, if there was a fluent API that allowed you to set these properties for the entire DbContext. In my case, I don't want to have to set it for each table. I would rather set it globally, but, MariaDB apparently doesn't let  you do that.

**Comment by Kagamine** [comment]
@caleblloyd Since we have supported dynamic typemapper, should we caculate the max varchar field length for different charset dynamically?

**Comment by jemiller0** [comment]
The issue that I ran into was the length of DECIMAL. It looked like it was WAY too big by default.

**Comment by caleblloyd** [comment]
@jemiller0 I set `decimal` to the max by default to avoid truncating people's numbers.  Really if you use a decimal column you should have a size in mind and set it explicitly.  Otherwise a `double` is a way better option.  In my opinion it's better to be over-protective here than to accidentally truncate somebody's decimal because we made an assumption.

**Comment by caleblloyd** [comment]
@Kagamine I would need to spend more time looking into the charset issue.  I think that setting it at the DB level is still the best way to go, or write a manual migration to change the charset.  Migrations can be modified before being applied.

**Comment by jemiller0** [comment]
@caleblloyd I need to look into it, but, I my initial take on it was that it was massive overkill. If it matches up with a C# decimal, then, I guess it makes sense. If it's bigger than that, then, it doesn't. The SQL Server provider defaults to DECIMAL(18, 2).

**Comment by jemiller0** [comment]
It says here https://msdn.microsoft.com/en-us/library/364x0z75(v=vs.140).aspx that C# decimal has a maximum precision of 29. You are defaulting to 65 for the precision and 30 for the scale. I agree that one should probably set this value explicitly, but, I prefer the defaults that Microsoft is using. For me anyway, I'm using decimal mostly for storing money values and Microsoft's defaults make sense for that. I think yours may be larger than what a C# decimal can even hold.

**Comment by Arcanst** [comment]
Hey, has anything been done about resolving this issue? I'm having some hard time altering every column in every table to use utf8 charset - even with workbench's help it's still not the way to go.

**Comment by Ciwan1859** [comment]
I create my database and tables through a custom `DatabaseInitializer.cs` and the database created is given a charset of `latin1`. Is there a way to tell the Pomelo library to use `utf8mb4` instead?

**Comment by erikbozic** [comment]
@Ciwan1859 I'm doing code first with migrations and solved this by manually adding this line at the start of `Up` of the initial migration:
``` c#
protected override void Up(MigrationBuilder migrationBuilder)
{
     migrationBuilder.Sql($@"ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;");
     \\ generated migration code
}
```
Don't know if it helps your case with the custom `DatabaseInitializer.cs`.

**Comment by Ciwan1859** [comment]
Thank you @erikbozic, I wasn't using migrations, but might start doing so now.

**Comment by caleblloyd** [comment]
We are addressing the issue of adding a default CharSet to columns in #553

**Comment by mylemans** [comment]
It is never fun if you come back after a long departure, run into an issue (I need to set ROW_FORMAT to DYNAMIC), and then to find a post made by myself 2 years ago for the same issue.. Any update? :/

**Comment by mguinness** [comment]
@mylemans CHARSET was resolved with PR https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/569.  No such setting exists for ROW_FORMAT right now.  Unless you've changed `innodb_default_row_format` the default should be DYNAMIC.  The workaround suggested by https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/84#issuecomment-253085911 should still work though.

**Comment by tonyawad88** [comment]
@erikbozic this works great. thank you. 
Any way of auto generating this line so that it doesn't get missed if a migration gets removed and re-added? 
`migrationBuilder.Sql($@"ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;");` 

Or is there another way of setting the charset and collate to the entire database? 

Thank you!

**Comment by dalibor-sanzeru** [comment]
I was facing to similar problem STORAGE ENGINE related to this issue:
- Default MYSQL Engine on externa MariaDB DB server is MYISAM, by generating new database using DbContext::Database::EnsureDatabaseCreated() are MYISAMs generated (Thats problem because of lack of FKs and Transaction support).

Solution:
- Using migrations (Instead of EnsureDatabaseCreated()) you can set innodb engine per db-session. (https://dev.mysql.com/doc/refman/5.7/en/storage-engine-setting.html)

protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("SET default_storage_engine=INNODB");
//Another migration code is generated here
}

In specific migration all tables are now INNODBs.

**Comment by jemiller0** [comment]
If it is still defaulting to MyISAM, that is absolutely ridiculous. The default should be InnoDB. I don't know a reason why anyone would want to use MyISAM, other than maybe performance. It should definitely not default to that.

**Comment by dalibor-sanzeru** [comment]
It was shared hosting with a lot of CMS stuff. Probably historical reasons.
Provided solution worked.

**Comment by AndrewZenith** [comment]
Is there still no easy way to just set the row format to compressed for all tables?
In MySql there is an option to set the default database type to InnoDB, but you can't set the default row format to compressed.
Does anyone have any code that can do this?

**Comment by lauxjpn** [comment]
> In MySql there is an option to set the default database type to InnoDB, but you can't set the default row format to compressed.

@AndrewZenith For InnoDB, there technically is, but it would be a `global` option (see [14.15 InnoDB Startup Options and System Variables: innodb_default_row_format](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_default_row_format)).

Other than that, currently a simple way to accomplish what you want would be to run an `ALTER TABLE` statement for each table:

```c#
using System.Collections.Generic;
using System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int IceCreamId { get; set; }
        public string Name { get; set; }
    }

    public class IceCreamBrand
    {
        public int IceCreamBrandId { get; set; }
        public string Name { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql(
                    "server=127.0.0.1;port=3308;user=root;password=;database=Issue84",
                    b => b.ServerVersion("8.0.20-mysql"))
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>(
                entity =>
                {
                    entity.HasData(
                        new IceCream {IceCreamId = 1, Name = "Vanilla"},
                        new IceCream {IceCreamId = 2, Name = "Chocolate"});
                });

            modelBuilder.Entity<IceCreamBrand>(
                entity =>
                {
                    entity.HasData(
                        new IceCreamBrand {IceCreamBrandId = 1, Name = "Cold as Ice"},
                        new IceCreamBrand {IceCreamBrandId = 2, Name = "Sweet as Candy"});
                });
        }

        public void ApplyTableOptions()
        {
            foreach (var table in GetTableNames())
            {
                // We don't use `ExecuteSqlInterpolated()`  here, because we don't want `table` to
                // be handled as a parameter.
                Database.ExecuteSqlRaw($@"ALTER TABLE `{table}` ROW_FORMAT = COMPRESSED;");
            }
        }

        private HashSet<string> GetTableNames()
        {
            var tables = new HashSet<string>();

            Database.OpenConnection();
            var connection = Database.GetDbConnection();

            using var command = connection.CreateCommand();
            command.CommandText = @"SELECT `TABLE_NAME`
    FROM `INFORMATION_SCHEMA`.`TABLES`
    WHERE `TABLE_SCHEMA` = SCHEMA() AND `TABLE_TYPE` = 'BASE TABLE';";

            using var dataReader = command.ExecuteReader();
            while (dataReader.Read())
            {
                tables.Add(dataReader.GetString("TABLE_NAME"));
            }

            return tables;
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
            context.ApplyTableOptions();
        }
    }
}
```

The generated SQL statements would look like this:

```sql
CREATE DATABASE `Issue84`;

CREATE TABLE `IceCreamBrand` (
    `IceCreamBrandId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_IceCreamBrand` PRIMARY KEY (`IceCreamBrandId`)
);

CREATE TABLE `IceCreams` (
    `IceCreamId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
);
INSERT INTO `IceCreamBrand` (`IceCreamBrandId`, `Name`)
VALUES (1, 'Cold as Ice');
INSERT INTO `IceCreamBrand` (`IceCreamBrandId`, `Name`)
VALUES (2, 'Sweet as Candy');

INSERT INTO `IceCreams` (`IceCreamId`, `Name`)
VALUES (1, 'Vanilla');
INSERT INTO `IceCreams` (`IceCreamId`, `Name`)
VALUES (2, 'Chocolate');

ALTER TABLE IceCreamBrand ROW_FORMAT = COMPRESSED;

ALTER TABLE IceCreams ROW_FORMAT = COMPRESSED;
```

---

Adding table options to Pomelo (through the Fluent API) would actually be pretty easy for us, so we should tackle this. Supporting all of them as defaults for new tables wouldn't be much harder. The latter would however not change the options of already existing tables.

**Comment by AndrewZenith** [comment]
Thanks for the swift response!
As for the global option that you referenced, in the text is: "The COMPRESSED row format, which is not supported for use in the system tablespace, cannot be defined as the default."
But the code looks great, and should get me sorted.  As you say however, it would be very nice to do this via the fluent API.

**Comment by unsafePtr** [comment]
In my case we had to use NDBCLUSTER engine in production. We agreed to set engine=NDBCLUSTER at DB level. When it doesn't present in the execution code. So migrations were applied properly

**Comment by pantonis** [comment]
@lauxjpn "Adding table options to Pomelo (through the Fluent API) would actually be pretty easy for us, so we should tackle this. Supporting all of them as defaults for new tables wouldn't be much harder. The latter would however not change the options of already existing tables" Was this implemented? I need to create some tables for different engine other than InnoDb and I need this on only specific tables. Can this be done using FluentApi. If not how can I do it then?

**Comment by pantonis** [comment]
Anyone ?
