### ISSUE TITLE
3.0: RenameColumn - SQL syntax error with MariaDB

### ISSUE THREAD

**Issue by PawelGerr** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#842]
A `MySqlException` is thrown when trying to rename a column using an EF migration.

### Migration command
```
migrationBuilder.RenameColumn(
                name: "OldName",
                table: "MyTable",
                newName: "NewName");
```
### Generated SQL statement
```
// 3.0.0-rc1.19480.1 - throws
ALTER TABLE `MyTable` RENAME COLUMN `OldName` `NewName`

// 2.2 - works
ALTER TABLE `MyTable` CHANGE `OldName` `NewName` bit NOT NULL DEFAULT FALSE;
```

### Exception
```
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `OldName` `NewName`' at line 1
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 772
```
Corresponding logger output
```
[15:11:38 ERR] [Microsoft.EntityFrameworkCore.Database.Command] Failed executing DbCommand (1,270,579ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `MyTable` RENAME COLUMN `OldName` `NewName`
```

### Further technical details
MariaDB version: 10.4.7
Operating system: Win10-x64
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc1.19480.1

**Comment by lauxjpn** [comment]
The MariaDB support has not been tested very thoroughly yet, so we appreciate any reports related to that.

The new `RENAME COLUMN` syntax should only be used by the provider on MySQL >= 8.0.0.
Did you explicitly set the `ServerVersion` for the `DbContext`? If not, the provider currently assumes MySQL 8.0.0.
This is likely to change before the 3.0.0 release, where the server version will be detected automatically.
See #832

**Comment by PawelGerr** [comment]
Nope, the version was missing but now I added it to the options builder:

```
builder
   .UseMySql(connectionString,
                     optionsBuilder => optionsBuilder.ServerVersion(
                                                            new Version(10,4,7),
                                                            ServerType.MariaDb))
```
Alas, I get the same error.

**Comment by PawelGerr** [comment]
The question is what version should I use in this case. 
According to [mariadb.com-compat](https://mariadb.com/kb/en/library/mariadb-vs-mysql-compatibility/) MariaDB 10.4 is "similar" to MySql 5.7.
Changing the version to 5.7 works in my case.

**Comment by lauxjpn** [comment]
Using the actual MariaDB version *should* be correct.
But it seems that we are not checking the version correctly here and your provided 10.4.7 is assumed to be the MySQL version (at least when generating the `RENAME COLUMN` statement) and thus >= 8.0.0.
Using the related MySQL version instead should work as a temporary workaround until we fixed this. Which will be shortly.

**Comment by PawelGerr** [comment]
> Using the related MySQL version instead should work as a temporary workaround until we fix this.

So is my plan :)

**Comment by bgrainger** [comment]
@lauxjpn MySqlConnector already has code to parse the server version, including the MariaDB suffix: https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/Core/ServerVersion.cs

It's currently `internal`; would that be useful to expose via a public API?

**Comment by lauxjpn** [comment]
@bgrainger This could be useful for the auto detection feature of #832. We are currently using this class for our checks and for setting the server version explicitly:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/9795a0a6013c1199f0cfc1f61293340773c9449d/src/EFCore.MySql/Storage/Internal/ServerVersion.cs#L10

The problem with the checks for the issue at hand is, that these check here do not differentiate between server types:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/9795a0a6013c1199f0cfc1f61293340773c9449d/src/EFCore.MySql/Storage/Internal/ServerVersion.cs#L49-L54

We need to either check the server type explicitly, or add some operators to the `ServerVersion` class, so we can compare different instances of themselves with each other instead of having to compare `ServerVersion.Version` and `ServerVersion.Type` manually, like here:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/9795a0a6013c1199f0cfc1f61293340773c9449d/src/EFCore.MySql/Storage/Internal/ServerVersion.cs#L70-L82

**Comment by bgrainger** [comment]
Oh, I didn't see there was already a `ServerVersion` type in this library (that already parses MySQL and MariaDB versions). It's such a small amount of code that it doesn't seem worth bothering figuring out how to share it.
