### ISSUE TITLE
NCHAR, NVARCHAR and UnicodeCharSet

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#894]
Currently `MySqlDbContextOptionsBuilder` contains an `AnsiCharSet` and a `UnicodeCharSet` extension method.
`MySqlTypeMappingSource` assumes Unicode for `nchar` and `nvarchar` types.

There might be some issues with that.

First of all we define the default `UnicodeCharSet` as `utf8mb4`:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/4740cb087ffc7045df8742ac1d4d4392a4b77bac/src/EFCore.MySql/Internal/MySqlOptions.cs#L16-L23

The official [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/charset-national.html) state the following however:

> Standard SQL defines NCHAR or NATIONAL CHAR as a way to indicate that a CHAR column should use some predefined character set. MySQL uses **utf8** as this predefined character set.

So the default for `nchar` and `nvarchar` should be `utf8`.

Also this charset seems to be predefined. So why do we provide the `UnicodeCharSet` extension method at all, if it cannot be changed?
I propose that we remove it.

Consequently we can rename `AnsiCharSet` to `CharSet`.

If no explicit charset is being specified, we should assume the default one for the used MySQL version, which is `latin1` < MySQL 8.0 >= `utf8mb4`.

Does anybody know, if MariaDB has made the move to `utf8mb4` as the default charset yet (and if so, in which version)?

**Comment by lauxjpn** [comment]
Looks like MariaDB is still using `latin1` as the default in `10.4`.

**Comment by bgrainger** [comment]
I'm not sure what these options control, but IMO all¹ string columns in MySQL should be explicitly declared as `utf8mb4` so they can store any Unicode character (i.e., what can be stored in `System.String`).

I don't think we need to detect or care what the server's default character set is; relying on server defaults instead of being explicit about column types just seems risky.

¹ Of course there could be exceptions; for example, a `Guid` column might want to be `CHAR(36) COLLATE ascii_general_ci` because it only needs to store `[A-Fa-f0-9]`. OTOH, if you are storing so many billions of GUIDs that optimising the storage for that column is important, `BINARY(16)` would be a lot more efficient choice, so caring about the column's character set might be overkill.

**Comment by lauxjpn** [comment]
I agree that if we want to make the move to use UTF8 as the default (meaning `utf8mb4`, as `utf8`/`utf8mb3` is basically a non-standard implementation today) we should do it now, as this could be a breaking change for someone.
The user could still set the charset manually using the options, but he would not be able to

**Comment by mguinness** [comment]
@caleblloyd Any comments on the suggested changes?
