### ISSUE TITLE
MySql.Data.MySqlClient.MySqlException: 'Access denied for user'

### ISSUE THREAD

**Issue by MKI-Miro** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#910]
### Steps to reproduce
Hi

First request to mariaDB 10.01 is successfull, but second throws error
MySql.Data.MySqlClient.MySqlException: 'Access denied for user'

password was not changed.
First call to DB is always successfull, no matter which code.

```
Exception message:
Stack trace:
MySql.Data.MySqlClient.MySqlException: 'Access denied for user'

### Further technical details

mariaDB 10.01
.NET Core 3
Pomelo 3 RC1

**Comment by lauxjpn** [comment]
We need more information.
Please provide us at least with
- The full exception including the stack trace
- The call in your code that leads to the exception
- Some general explanation what is going on at the time of the exception

It is possible that this is related to #908, but with the limited information we have right now, we can't really tell.

**Comment by MKI-Miro** [comment]
calling twice this function leads in error

`public List<CategoryManufacturer> GetAllManufacturers()
        {
            using (var context = new dbContext())
            {
                var result = context.CategoryManufacturer.ToList();

                return result; 
            }
        }`

stackTrace

`   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySqlConnector.Core.ServerSession.<TryResetConnectionAsync>d__69.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 493
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 72
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__107.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 610
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__26.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 310
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 277
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PuzzleManiaCore.ManiaManufacturerService.GetAllManufacturers() in C:\Users\mki\Source\Workspaces\Omega\PuzzleManiaCore\ManiaManufacturerService.cs:line 13`

**Comment by lauxjpn** [comment]
How does your `DbContext` look like? Especially the `.UseMySql()` call?

**Comment by MKI-Miro** [comment]
> How does your `DbContext` look like? Especially the `.UseMySql()` call?

I havent changed anything there

`protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseMySql("server=XXX;port=3312;user id=XXX;password=XXX;database=XXX;TreatTinyAsBoolean=false");
            }
        }`

**Comment by MKI-Miro** [comment]
I just tried to upgrade to  MariaDb 10.03 and it works

**Comment by lauxjpn** [comment]
Glad to hear, that an upgrade solved the issue for you.

The problem is likely a configuration issue on your end, as the following code works fine for me with MariaDB 10.1.41:

```c#
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class TestEntity
    {
        public int Id { get; set; }
        public int MyValue { get; set; }
    }

    public class Issue910Context : DbContext
    {
        public DbSet<TestEntity> TestEntities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // MariaDB 10.1.41
            optionsBuilder
                .UseMySql("server=127.0.0.1;port=33101;user=issue910user;password=asdf;database=Issue910")
                .UseLoggerFactory(LoggerFactory.Create(b => b
                    .AddConsole()
                    .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TestEntity>()
                .HasData(new TestEntity { Id = 1, MyValue = 42 });
        }
    }

    internal class Program
    {
        private static void Main()
        {
            using var context = new Issue910Context();

            context.Database.EnsureCreated();

            ExecuteNewDbContextOperation();
            ExecuteNewDbContextOperation();
            ExecuteNewDbContextOperation();
        }

        private static void ExecuteNewDbContextOperation()
        {
            using var context = new Issue910Context();
            
            var result = context.TestEntities.ToList();

            Debug.Assert(result.Count == 1);
            Debug.Assert(result[0].MyValue == 42);
        }
    }
}
```

With the following log messages:

```sql
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.2-rtm-30932 initialized 'Issue910Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: SensitiveDataLoggingEnabled
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

                    SELECT CASE WHEN COUNT(*) = 0 THEN FALSE ELSE TRUE END
                    FROM information_schema.tables
                    WHERE table_type = 'BASE TABLE' AND table_schema = 'Issue910'
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.2-rtm-30932 initialized 'Issue910Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: SensitiveDataLoggingEnabled
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `t`.`Id`, `t`.`MyValue`
      FROM `TestEntities` AS `t`
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.2-rtm-30932 initialized 'Issue910Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: SensitiveDataLoggingEnabled
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `t`.`Id`, `t`.`MyValue`
      FROM `TestEntities` AS `t`
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.2-rtm-30932 initialized 'Issue910Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: SensitiveDataLoggingEnabled
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `t`.`Id`, `t`.`MyValue`
      FROM `TestEntities` AS `t`
```

If you want to compare your system variables, run `show variables;` and compare the result to mine:

<details>
<summary>Expand to see all my system variables</summary>

Variable_name | Value
-- | --
aria_block_size | 8192
aria_checkpoint_interval | 30
aria_checkpoint_log_activity | 1048576
aria_encrypt_tables | OFF
aria_force_start_after_recovery_failures | 0
aria_group_commit | none
aria_group_commit_interval | 0
aria_log_file_size | 1073741824
aria_log_purge_type | immediate
aria_max_sort_file_size | 9223372036853727232
aria_page_checksum | ON
aria_pagecache_age_threshold | 300
aria_pagecache_buffer_size | 134217728
aria_pagecache_division_limit | 100
aria_pagecache_file_hash_size | 512
aria_recover | NORMAL
aria_repair_threads | 1
aria_sort_buffer_size | 268434432
aria_stats_method | nulls_unequal
aria_sync_log_dir | NEWFILE
aria_used_for_temp_tables | ON
auto_increment_increment | 1
auto_increment_offset | 1
autocommit | ON
automatic_sp_privileges | ON
back_log | 80
basedir | D:\Program Files\MariaDB 10.1\
big_tables | OFF
binlog_annotate_row_events | OFF
binlog_cache_size | 32768
binlog_checksum | NONE
binlog_commit_wait_count | 0
binlog_commit_wait_usec | 100000
binlog_direct_non_transactional_updates | OFF
binlog_format | STATEMENT
binlog_optimize_thread_scheduling | ON
binlog_row_image | FULL
binlog_stmt_cache_size | 32768
bulk_insert_buffer_size | 8388608
character_set_client | utf8mb4
character_set_connection | utf8mb4
character_set_database | latin1
character_set_filesystem | binary
character_set_results | utf8mb4
character_set_server | latin1
character_set_system | utf8
character_sets_dir | D:\Program Files\MariaDB 10.1\share\charsets\
collation_connection | utf8mb4_general_ci
collation_database | latin1_swedish_ci
collation_server | latin1_swedish_ci
completion_type | NO_CHAIN
concurrent_insert | AUTO
connect_timeout | 10
core_file | OFF
datadir | E:\Databases\MariaDB\MariaDB 10.1\data\
date_format | %Y-%m-%d
datetime_format | %Y-%m-%d %H:%i:%s
deadlock_search_depth_long | 15
deadlock_search_depth_short | 4
deadlock_timeout_long | 50000000
deadlock_timeout_short | 10000
debug_no_thread_alarm | OFF
default_master_connection | 
default_regex_flags | 
default_storage_engine | InnoDB
default_tmp_storage_engine | 
default_week_format | 0
delay_key_write | ON
delayed_insert_limit | 100
delayed_insert_timeout | 300
delayed_queue_size | 1000
div_precision_increment | 4
encrypt_binlog | OFF
encrypt_tmp_disk_tables | OFF
encrypt_tmp_files | OFF
enforce_storage_engine | 
error_count | 0
event_scheduler | OFF
expensive_subquery_limit | 100
expire_logs_days | 0
explicit_defaults_for_timestamp | OFF
external_user | 
extra_max_connections | 1
extra_port | 0
flush | OFF
flush_time | 0
foreign_key_checks | ON
ft_boolean_syntax | + -><()~*:""&|
ft_max_word_len | 84
ft_min_word_len | 4
ft_query_expansion_limit | 20
ft_stopword_file | (built-in)
general_log | OFF
general_log_file | MYMACHINENAME.log
group_concat_max_len | 1024
gtid_binlog_pos | 
gtid_binlog_state | 
gtid_current_pos | 
gtid_domain_id | 0
gtid_ignore_duplicates | OFF
gtid_seq_no | 0
gtid_slave_pos | 
gtid_strict_mode | OFF
have_compress | YES
have_crypt | NO
have_dynamic_loading | YES
have_geometry | YES
have_openssl | NO
have_profiling | YES
have_query_cache | YES
have_rtree_keys | YES
have_ssl | DISABLED
have_symlink | NO
histogram_size | 0
histogram_type | SINGLE_PREC_HB
host_cache_size | 279
hostname | MYMACHINENAME
identity | 0
ignore_builtin_innodb | OFF
ignore_db_dirs | 
in_transaction | 0
init_connect | 
init_file | 
init_slave | 
innodb_adaptive_flushing | ON
innodb_adaptive_flushing_lwm | 10.000000
innodb_adaptive_hash_index | ON
innodb_adaptive_hash_index_partitions | 1
innodb_adaptive_max_sleep_delay | 150000
innodb_additional_mem_pool_size | 8388608
innodb_api_bk_commit_interval | 5
innodb_api_disable_rowlock | OFF
innodb_api_enable_binlog | OFF
innodb_api_enable_mdl | OFF
innodb_api_trx_level | 0
innodb_autoextend_increment | 64
innodb_autoinc_lock_mode | 1
innodb_background_scrub_data_check_interval | 3600
innodb_background_scrub_data_compressed | OFF
innodb_background_scrub_data_interval | 604800
innodb_background_scrub_data_uncompressed | OFF
innodb_buf_dump_status_frequency | 0
innodb_buffer_pool_dump_at_shutdown | OFF
innodb_buffer_pool_dump_now | OFF
innodb_buffer_pool_dump_pct | 100
innodb_buffer_pool_filename | ib_buffer_pool
innodb_buffer_pool_instances | 8
innodb_buffer_pool_load_abort | OFF
innodb_buffer_pool_load_at_startup | OFF
innodb_buffer_pool_load_now | OFF
innodb_buffer_pool_populate | OFF
innodb_buffer_pool_size | 2106589184
innodb_change_buffer_max_size | 25
innodb_change_buffering | all
innodb_checksum_algorithm | INNODB
innodb_checksums | ON
innodb_cleaner_lsn_age_factor | HIGH_CHECKPOINT
innodb_cmp_per_index_enabled | OFF
innodb_commit_concurrency | 0
innodb_compression_algorithm | zlib
innodb_compression_failure_threshold_pct | 5
innodb_compression_level | 6
innodb_compression_pad_pct_max | 50
innodb_concurrency_tickets | 5000
innodb_corrupt_table_action | assert
innodb_data_file_path | ibdata1:12M:autoextend
innodb_data_home_dir | 
innodb_default_encryption_key_id | 1
innodb_default_row_format | compact
innodb_defragment | OFF
innodb_defragment_fill_factor | 0.900000
innodb_defragment_fill_factor_n_recs | 20
innodb_defragment_frequency | 40
innodb_defragment_n_pages | 7
innodb_defragment_stats_accuracy | 0
innodb_disable_sort_file_cache | OFF
innodb_doublewrite | ON
innodb_empty_free_list_algorithm | BACKOFF
innodb_encrypt_log | OFF
innodb_encrypt_tables | OFF
innodb_encryption_rotate_key_age | 1
innodb_encryption_rotation_iops | 100
innodb_encryption_threads | 0
innodb_fake_changes | OFF
innodb_fast_shutdown | 1
innodb_fatal_semaphore_wait_threshold | 600
innodb_file_format | Antelope
innodb_file_format_check | ON
innodb_file_format_max | Antelope
innodb_file_per_table | ON
innodb_flush_log_at_timeout | 1
innodb_flush_log_at_trx_commit | 1
innodb_flush_method | 
innodb_flush_neighbors | 1
innodb_flushing_avg_loops | 30
innodb_force_load_corrupted | OFF
innodb_force_primary_key | OFF
innodb_force_recovery | 0
innodb_foreground_preflush | EXPONENTIAL_BACKOFF
innodb_ft_aux_table | 
innodb_ft_cache_size | 8000000
innodb_ft_enable_diag_print | OFF
innodb_ft_enable_stopword | ON
innodb_ft_max_token_size | 84
innodb_ft_min_token_size | 3
innodb_ft_num_word_optimize | 2000
innodb_ft_result_cache_limit | 2000000000
innodb_ft_server_stopword_table | 
innodb_ft_sort_pll_degree | 2
innodb_ft_total_cache_size | 640000000
innodb_ft_user_stopword_table | 
innodb_idle_flush_pct | 100
innodb_immediate_scrub_data_uncompressed | OFF
innodb_instrument_semaphores | OFF
innodb_io_capacity | 200
innodb_io_capacity_max | 2000
innodb_kill_idle_transaction | 0
innodb_large_prefix | OFF
innodb_lock_schedule_algorithm | fcfs
innodb_lock_wait_timeout | 50
innodb_locking_fake_changes | ON
innodb_locks_unsafe_for_binlog | OFF
innodb_log_arch_dir | .\
innodb_log_arch_expire_sec | 0
innodb_log_archive | OFF
innodb_log_block_size | 512
innodb_log_buffer_size | 16777216
innodb_log_checksum_algorithm | INNODB
innodb_log_compressed_pages | ON
innodb_log_file_size | 52428800
innodb_log_files_in_group | 2
innodb_log_group_home_dir | .\
innodb_lru_scan_depth | 1024
innodb_max_bitmap_file_size | 104857600
innodb_max_changed_pages | 1000000
innodb_max_dirty_pages_pct | 75.000000
innodb_max_dirty_pages_pct_lwm | 0.001000
innodb_max_purge_lag | 0
innodb_max_purge_lag_delay | 0
innodb_mirrored_log_groups | 1
innodb_monitor_disable | 
innodb_monitor_enable | 
innodb_monitor_reset | 
innodb_monitor_reset_all | 
innodb_mtflush_threads | 8
innodb_old_blocks_pct | 37
innodb_old_blocks_time | 1000
innodb_online_alter_log_max_size | 134217728
innodb_open_files | 2000
innodb_optimize_fulltext_only | OFF
innodb_page_size | 16384
innodb_prefix_index_cluster_optimization | OFF
innodb_print_all_deadlocks | OFF
innodb_print_lock_wait_timeout_info | OFF
innodb_purge_batch_size | 300
innodb_purge_threads | 1
innodb_random_read_ahead | OFF
innodb_read_ahead_threshold | 56
innodb_read_io_threads | 4
innodb_read_only | OFF
innodb_replication_delay | 0
innodb_rollback_on_timeout | OFF
innodb_rollback_segments | 128
innodb_scrub_log | OFF
innodb_scrub_log_speed | 256
innodb_show_locks_held | 10
innodb_show_verbose_locks | 0
innodb_simulate_comp_failures | 0
innodb_sort_buffer_size | 1048576
innodb_spin_wait_delay | 6
innodb_stats_auto_recalc | ON
innodb_stats_include_delete_marked | OFF
innodb_stats_method | nulls_equal
innodb_stats_modified_counter | 0
innodb_stats_on_metadata | OFF
innodb_stats_persistent | ON
innodb_stats_persistent_sample_pages | 20
innodb_stats_sample_pages | 8
innodb_stats_traditional | ON
innodb_stats_transient_sample_pages | 8
innodb_status_output | OFF
innodb_status_output_locks | OFF
innodb_strict_mode | OFF
innodb_support_xa | ON
innodb_sync_array_size | 1
innodb_sync_spin_loops | 30
innodb_table_locks | ON
innodb_thread_concurrency | 0
innodb_thread_sleep_delay | 10000
innodb_tmpdir | 
innodb_track_changed_pages | OFF
innodb_undo_directory | .
innodb_undo_logs | 128
innodb_undo_tablespaces | 0
innodb_use_atomic_writes | OFF
innodb_use_fallocate | OFF
innodb_use_global_flush_log_at_trx_commit | ON
innodb_use_mtflush | OFF
innodb_use_native_aio | ON
innodb_use_stacktrace | OFF
innodb_use_sys_malloc | ON
innodb_use_trim | OFF
innodb_version | 5.6.44-86.0
innodb_write_io_threads | 4
insert_id | 0
interactive_timeout | 28800
join_buffer_size | 262144
join_buffer_space_limit | 2097152
join_cache_level | 2
keep_files_on_create | OFF
key_buffer_size | 134217728
key_cache_age_threshold | 300
key_cache_block_size | 1024
key_cache_division_limit | 100
key_cache_file_hash_size | 512
key_cache_segments | 0
large_files_support | ON
large_page_size | 0
large_pages | OFF
last_gtid | 
last_insert_id | 0
lc_messages | en_US
lc_messages_dir | 
lc_time_names | en_US
license | GPL
local_infile | ON
lock_wait_timeout | 31536000
log_bin | OFF
log_bin_basename | 
log_bin_index | 
log_bin_trust_function_creators | OFF
log_error | E:\Databases\MariaDB\MariaDB 10.1\data\MYMACHINENAME.err
log_output | FILE
log_queries_not_using_indexes | OFF
log_slave_updates | OFF
log_slow_admin_statements | OFF
log_slow_filter | admin,filesort,filesort_on_disk,full_join,full_scan,query_cache,query_cache_miss,tmp_table,tmp_table_on_disk
log_slow_rate_limit | 1
log_slow_slave_statements | OFF
log_slow_verbosity | 
log_tc_size | 24576
log_warnings | 1
long_query_time | 10.000000
low_priority_updates | OFF
lower_case_file_system | ON
lower_case_table_names | 1
master_verify_checksum | OFF
max_allowed_packet | 4194304
max_binlog_cache_size | 18446744073709547520
max_binlog_size | 1073741824
max_binlog_stmt_cache_size | 18446744073709547520
max_connect_errors | 100
max_connections | 151
max_delayed_threads | 20
max_digest_length | 1024
max_error_count | 64
max_heap_table_size | 16777216
max_insert_delayed_threads | 20
max_join_size | 18446744073709551615
max_length_for_sort_data | 1024
max_long_data_size | 4194304
max_prepared_stmt_count | 16382
max_relay_log_size | 1073741824
max_seeks_for_key | 4294967295
max_session_mem_used | 9223372036854775807
max_sort_length | 1024
max_sp_recursion_depth | 0
max_statement_time | 0.000000
max_tmp_tables | 32
max_user_connections | 0
max_write_lock_count | 4294967295
metadata_locks_cache_size | 1024
metadata_locks_hash_instances | 8
min_examined_row_limit | 0
mrr_buffer_size | 262144
multi_range_count | 256
myisam_block_size | 1024
myisam_data_pointer_size | 6
myisam_max_sort_file_size | 2146435072
myisam_mmap_size | 18446744073709551615
myisam_recover_options | DEFAULT
myisam_repair_threads | 1
myisam_sort_buffer_size | 134216704
myisam_stats_method | NULLS_UNEQUAL
myisam_use_mmap | OFF
mysql56_temporal_format | ON
named_pipe | OFF
net_buffer_length | 16384
net_read_timeout | 30
net_retry_count | 10
net_write_timeout | 60
old | OFF
old_alter_table | OFF
old_mode | 
old_passwords | OFF
open_files_limit | 6230
optimizer_prune_level | 1
optimizer_search_depth | 62
optimizer_selectivity_sampling_limit | 100
optimizer_switch | index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materia...
optimizer_use_condition_selectivity | 1
performance_schema | OFF
performance_schema_accounts_size | -1
performance_schema_digests_size | -1
performance_schema_events_stages_history_long_size | -1
performance_schema_events_stages_history_size | -1
performance_schema_events_statements_history_long_size | -1
performance_schema_events_statements_history_size | -1
performance_schema_events_waits_history_long_size | -1
performance_schema_events_waits_history_size | -1
performance_schema_hosts_size | -1
performance_schema_max_cond_classes | 80
performance_schema_max_cond_instances | -1
performance_schema_max_digest_length | 1024
performance_schema_max_file_classes | 50
performance_schema_max_file_handles | 32768
performance_schema_max_file_instances | -1
performance_schema_max_mutex_classes | 200
performance_schema_max_mutex_instances | -1
performance_schema_max_rwlock_classes | 40
performance_schema_max_rwlock_instances | -1
performance_schema_max_socket_classes | 10
performance_schema_max_socket_instances | -1
performance_schema_max_stage_classes | 150
performance_schema_max_statement_classes | 178
performance_schema_max_table_handles | -1
performance_schema_max_table_instances | -1
performance_schema_max_thread_classes | 50
performance_schema_max_thread_instances | -1
performance_schema_session_connect_attrs_size | -1
performance_schema_setup_actors_size | 100
performance_schema_setup_objects_size | 100
performance_schema_users_size | -1
pid_file | E:\Databases\MariaDB\MariaDB 10.1\data\MYMACHINENAME.pid
plugin_dir | D:\Program Files\MariaDB 10.1\lib\plugin\
plugin_maturity | unknown
port | 33101
preload_buffer_size | 32768
profiling | OFF
profiling_history_size | 15
progress_report_time | 5
protocol_version | 10
proxy_user | 
pseudo_slave_mode | OFF
pseudo_thread_id | 46
query_alloc_block_size | 16384
query_cache_limit | 1048576
query_cache_min_res_unit | 4096
query_cache_size | 1048576
query_cache_strip_comments | OFF
query_cache_type | OFF
query_cache_wlock_invalidate | OFF
query_prealloc_size | 24576
rand_seed1 | 44313746
rand_seed2 | 177261016
range_alloc_block_size | 4096
read_buffer_size | 131072
read_only | OFF
read_rnd_buffer_size | 262144
relay_log | 
relay_log_basename | 
relay_log_index | 
relay_log_info_file | relay-log.info
relay_log_purge | ON
relay_log_recovery | OFF
relay_log_space_limit | 0
replicate_annotate_row_events | OFF
replicate_do_db | 
replicate_do_table | 
replicate_events_marked_for_skip | REPLICATE
replicate_ignore_db | 
replicate_ignore_table | 
replicate_wild_do_table | 
replicate_wild_ignore_table | 
report_host | 
report_password | 
report_port | 33101
report_user | 
rowid_merge_buff_size | 8388608
secure_auth | ON
secure_file_priv | 
server_id | 0
shared_memory | OFF
shared_memory_base_name | MYSQL
skip_external_locking | ON
skip_name_resolve | OFF
skip_networking | OFF
skip_parallel_replication | OFF
skip_replication | OFF
skip_show_database | OFF
slave_compressed_protocol | OFF
slave_ddl_exec_mode | IDEMPOTENT
slave_domain_parallel_threads | 0
slave_exec_mode | STRICT
slave_load_tmpdir | C:\WINDOWS\SERVIC~1\NETWOR~1\AppData\Local\Temp
slave_max_allowed_packet | 1073741824
slave_net_timeout | 3600
slave_parallel_max_queued | 131072
slave_parallel_mode | conservative
slave_parallel_threads | 0
slave_run_triggers_for_rbr | NO
slave_skip_errors | OFF
slave_sql_verify_checksum | ON
slave_transaction_retries | 10
slave_type_conversions | 
slow_launch_time | 2
slow_query_log | OFF
slow_query_log_file | MYMACHINENAME-slow.log
socket | MySQL
sort_buffer_size | 2097152
sql_auto_is_null | OFF
sql_big_selects | ON
sql_buffer_result | OFF
sql_log_bin | ON
sql_log_off | OFF
sql_mode | STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
sql_notes | ON
sql_quote_show_create | ON
sql_safe_updates | OFF
sql_select_limit | 18446744073709551615
sql_slave_skip_counter | 0
sql_warnings | OFF
ssl_ca | 
ssl_capath | 
ssl_cert | 
ssl_cipher | 
ssl_crl | 
ssl_crlpath | 
ssl_key | 
storage_engine | InnoDB
stored_program_cache | 256
strict_password_validation | ON
sync_binlog | 0
sync_frm | ON
sync_master_info | 10000
sync_relay_log | 10000
sync_relay_log_info | 10000
system_time_zone | Europe/Berlin
table_definition_cache | 400
table_open_cache | 2000
thread_cache_size | 0
thread_concurrency | 10
thread_handling | pool-of-threads
thread_pool_max_threads | 1000
thread_pool_min_threads | 1
thread_stack | 299008
time_format | %H:%i:%s
time_zone | SYSTEM
timed_mutexes | OFF
timestamp | 1572949681.829820
tmp_table_size | 16777216
tmpdir | C:\WINDOWS\SERVIC~1\NETWOR~1\AppData\Local\Temp
transaction_alloc_block_size | 8192
transaction_prealloc_size | 4096
tx_isolation | REPEATABLE-READ
tx_read_only | OFF
unique_checks | ON
updatable_views_with_limit | YES
use_stat_tables | NEVER
userstat | OFF
version | 10.1.41-MariaDB
version_comment | mariadb.org binary distribution
version_compile_machine | x64
version_compile_os | Win64
version_malloc_library | system
version_ssl_library | YaSSL 2.4.4
wait_timeout | 28800
warning_count | 0

</details>
