### ISSUE TITLE
Scaffold HasCharSet generation for tables

### ISSUE THREAD

**Issue by mguinness** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#913]
Investigate omitting `HasCharSet()` when the column charset matches the table, to align with [Column Character Set and Collation](https://dev.mysql.com/doc/refman/8.0/en/charset-column.html).

We would have to annotate the entity with the table's charset (like we do with properties and their columns now) to support that.

**Comment by lauxjpn** [comment]
Additionally, we can think about making the `HasCharSet()` scaffolding optional. For example, a connection string pseudo-option like `Scaffold:CharSets=true` could be introduced, with a reasonable default value.

Pomelo and MySqlConnector are using `System.String` internally and MySqlConnector is using `utf8mb4` for all its server communication on the wire.

So the `HasCharSet()` calls really only matter, if the migration code needs to create tables with the exact same characteristics of the source tables it was created of. That should only be needed, if external dependencies on the database exists (e.g. other apps).

For those scenarios, supporting collations would be the next step, as these are not used by Pomelo either, while external apps could depend on them.

**Comment by mguinness** [comment]
It looks like there is a discussion about `RelationalTypeMapping` in https://github.com/aspnet/EntityFrameworkCore/issues/11896 so maybe @roji can give some input.

What would be neat is if charset is `latin1` that the following data annotation could be added to the model validation to avoid data loss.

```C#
[RegularExpression(@"^[\x20-\x7E\xA0-\xFF]+$", ErrorMessage = "Only ANSI characters accepted")]
public string Name { get; set; }
```

**Comment by lauxjpn** [comment]
Only scaffolding the column charset if it is different from the tables default charset might lead to unexpected behavior later on.

This is due to the fact, that if no charset is defined for a column at creation time, MySQL creates the column with the tables default charset. If at a point later in time, the tables default charset is changed, the charset of the column that was created using the tables default charset will stay unchanged.

Let's assume the following initial model definition:

```c#
modelBuilder.Entity<MyEntity>(entity =>
    entity.HasCharSet("latin1");

    entity.Property(e => e.TextProperty)
        .HasMaxLength(255);
});
```

When this model is created, `TextProperty` will have a charset of `latin1`.
We later change the default charset:

```c#
modelBuilder.Entity<MyEntity>(entity =>
    entity.HasCharSet("utf8mb4");

    entity.Property(e => e.TextProperty)
        .HasMaxLength(255);
});
```

If migrations are being used for all schema changes, then `TextProperty` would still be `latin1` after applying the new migration.

In contrast to that, `TextProperty` would be `utf8mb4`, if the database would be created from scratch now, by using:

```c#
context.Database.EnsureDeleted();
context.Database.EnsureCreated();
```

This might be unexpected for users who assume, that calling `HasCharSet()` on the entity has the same effect as calling it on every string property.

It gets worse, as using `ALTER TABLE CHANGE COLUMN` to rename a column (MySQL < 8.0.0) would reset the column to the tables default charset (because no explicit column charset has been set), and `ALTER TABLE RENAME COLUMN` to rename a column (MySQL >= 8.0.0) keeps the columns current charset.

By limiting the use of `HasCharSet()` to properties/columns, this will not be an issue.

There are other implementation possibilities:
- Naming the extension method more explicit for entities, something like `HasDefaultAddColumnCharSet()` or `HasColumnCreationCharSet()`. But `ALTER TABLE CHANGE COLUMN` statements would still be a problem.
- Using `HasCharSet()` on an entity as an actual shorthand for using it on every property in addition to setting the tables default charset. This would need much more additional plumbing, because changing the annotation on the entity would need to generated column modification operations in addition the `ALTER TABLE` statement to change the tables default charset.

**Comment by mguinness** [comment]
That is a very good explanation of the issues involved.  Based on your conclusions I agree that it's best to explicitly specify `HasCharSet()` on the fields to avoid any ambiguity.

**Comment by lauxjpn** [comment]
We can always dive deeper into this this feature and its possible solutions, if users demand it.

**Comment by roji** [comment]
@mcguiness 

> It looks like there is a discussion about RelationalTypeMapping in aspnet/EntityFrameworkCore#11896 so maybe @roji can give some input.

Yeah, the store name management on the relational type mapping could be better, but could you guys provide a bit more details about what exactly you need or where you're blocking?

> Using HasCharSet() on an entity as an actual shorthand for using it on every property in addition to setting the tables default charset. This would need much more additional plumbing, because changing the annotation on the entity would need to generated column modification operations in addition the ALTER TABLE statement to change the tables default charset.

This typically isn't a huge deal, and probably resembles how SqlServer and Npgsql allow setting the default value generation strategy at the model level, but allowing it to be overridden on an property-by-property basis. So if this kind of thing makes sense for you, I wouldn't dismiss it too quickly because of implementation/plumbing concerns. In fact, you may want to even have it on the model level.

**Comment by lauxjpn** [comment]
@roji I agree that this is definitely possible to implement and the option you quoted is also the favorite one as it is the least ambiguous. For me it's more a question of whether users really need/want this feature and how much of a priority it is.

But it might be a good idea to at least keep this issue open, so users already have a place to participate in the discussion around it. If the user resonance is there for this feature, we can implement it for `3.1.0`, so it will officially share compatibility with the LTS release.

@mguinness What do you think?

**Comment by mguinness** [comment]
I've reopened as it would be good to get feedback from users.  I don't think it's something in demand, but we'll get an idea after 3.0 gets more widespread use.  I'm glad roji was able to share his thoughts as we've often referred to the Npgsql provider for inspiration when implementing features.
