### ISSUE TITLE
Scaffold-DbContext generates properties of type `ulong` instead of `bool` for `bit(1)` database columns

### ISSUE THREAD

**Issue by spewu** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#917]
### Steps to reproduce
If you have a column of the type `bit(1)`, then the scaffolder in rc1 would produce a `bool` property on the model.

In rc2 it produces a property with the type `ulong`.

### Further technical details

MySQL version: 8.0.16
Operating system: macOS 10.15.1 (MySQL running in a Linux Docker)
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc2.final
Microsoft.AspNetCore.App version: 3.0

**Comment by lauxjpn** [comment]
This is an expected breaking change introduced in `3.0.0-rc2` (see #866, #875 and #656):

> Because `bit` was previously hard-mapped to `System.Boolean` and now isn't (it is now mapped to `System.UInt64` in all cases, unless `TreatTinyAsBoolean=false`, in which case `bit(1)` is mapped to `System.Boolean` and all other `bit` lengths are mapped to `System.UInt64`), this has the potential of being a **breaking change** for someone.

The default behavior to map database columns to `System.Boolean` in `3.0.0-rc2` is to use the [connection string option](https://mysqlconnector.net/connection-options/) `TreatTinyAsBoolean=True`, which is the default for MySqlConnector (the underlying library we use for database communication).

With `TreatTinyAsBoolean=True` (the default), database columns defined as `tinyint(1)` will be mapped to properties of type `System.Boolean`. This is in line with MySQL, that defines `bool` as an alias of `tinyint(1)`.

With `TreatTinyAsBoolean=False`, the previous behavior of mapping database columns defined as `bit(1)` to type `System.Boolean` will be used.

**Comment by miggat** [comment]
Hello, I'm on release 3.0.0 trying to run the scaffold command with TreatTinyAsBoolean=False on MySql 8.0.17, but the BIT(1) columns are still generated as ulong (same with TreatTinyAsBoolean=True):

```
        [Column("isMain", TypeName = "bit(1)")]
        public ulong IsMain { get; set; }
```

**Comment by lauxjpn** [comment]
@miggat Thank you for reporting this issue! This bug was introduced last minute when we removed the server version auto detection support with #944.
We have planed to release a `3.0.1` version shortly, which will include the fix to this issue among others.

**Comment by startewho** [comment]
I used the lastest 3.1Rc1.and when setting the connext string
 `TreatTinyAsBoolean=false`,it will convert bit to bool,
but when i  set
`TreatTinyAsBoolean=true`,
it still convert bit(1) to ulong;
Is it as expected?

**Comment by lauxjpn** [comment]
@startewho Yes, that is the expected behavior. Any `bit` store type will be translated to `System.UInt64` (while `tinyint(1)` will be translated to `System.Boolean`), unless either `TreatTinyAsBoolean=false` or `mySqlOptions.DefaultDataTypeMappings(m => m.WithClrBoolean(MySqlBooleanType.Bit1))` has been set, in which case only `bit(1)` will be translated to `System.Boolean` while other `bit` sizes are still being translated to `System.UInt64`.

**Comment by lauxjpn** [comment]
@krishKM I always thought that translating bit fields of different sizes to a .NET type of `System.UInt64` by default makes practically a lot of sense, since those fields are likely to be used for flags etc.

Please elaborate what .NET datatype you would suggest to translate a `bit` store type of different sizes to and why. Maybe there is a common case that we didn't think about.
