### ISSUE TITLE
Method 'get_Info' in type  xxx   does not have an implementation  .???

### ISSUE THREAD

**Issue by chenzhenghong** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#924]
### The issue

 not support   3.0 ？？

Method 'get_Info' in type 'Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal.MySqlOptionsExtension' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=2.2.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.”

Exception message:
Stack trace:
```

### Further technical details

MySQL version:8.0.18 
Operating system: win10
Pomelo.EntityFrameworkCore.MySql version: 2.2.6
Microsoft.AspNetCore.App version:3.0.0

**Comment by lauxjpn** [comment]
Please use the search function, because this has been discussed many times, for example:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/797
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/825#issuecomment-534698769

You are using Pomelo `2.2.6` together with EF Core `3.0.0`, which is not supported.

---

You can find the **Compatibility** table on the first page of this repository:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#ef-core-and-net-core

Pomelo.EntityFrameworkCore.MySql | EF Core | .NET Core
-- | -- | --
[3.0.0-rc3.final](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.0.0-rc3.final) (prerelease) | 3.0.0 | 3.0
[2.2.6](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.2.6) | 2.2.6 | 2.2 / 3.0
