### ISSUE TITLE
Client side GroupBy is not supported

### ISSUE THREAD

**Issue by luoqining** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#934]
When use query like this:

db.meter_info.GroupBy(p=>p.meter_comm_no).ToList();

It throw the exception:
"Client side GroupBy is not supported"

MySQL version: 5.7
Operating system: win10 x64
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc3.final
Microsoft.AspNetCore.App version: net core 3.0

Pomelo.EntityFrameworkCore.MySql version 2.2.6,net core 2.2 is OK.

**Comment by lauxjpn** [comment]
This is a known limitation in EF Core, that stems from the very different concepts between LINQs `GroupBy()` and SQLs `GROUP BY`.
See [Group By on MSDN](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#groupby) for further details.

If this worked in 2.2, it is because EF Core 2.2 implicitly uses client evaluation as a fallback, it it cannot generate an appropriate query, while EF Core 3.0 does not.

---

As an example, assume the following code:

```c#
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Popularity { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql("server=127.0.0.1;port=3306;user=root;password=;database=Issue934")
                .UseLoggerFactory(LoggerFactory.Create(b => b
                    .AddConsole()
                    .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>()
                .HasData(
                    new IceCream {Id = 1, Name = "Vanilla", Popularity = 3},
                    new IceCream {Id = 2, Name = "Chocolate", Popularity = 3},
                    new IceCream {Id = 3, Name = "Strawberry", Popularity = 2},
                    new IceCream {Id = 4, Name = "Matcha", Popularity = 1}
                );
        }
    }

    internal class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var groups = context.IceCreams
                .GroupBy(i => i.Popularity)
                .OrderByDescending(g => g.Key)
                .ToList();

            Debug.Assert(groups.Count == 3);
            Debug.Assert(groups[0].Count() == 2);
        }
    }
}
```

This will throw an exception, because we directly use the `GroupBy()` extension method, that returns an `IGrouping<>`, containing the individual `IceCream` objects, while SQLs `GROUP BY` clause cannot return those, but instead aggregates columns, which would result in a custom type that is not compatible with the `IceCream` class.

The following change will work however:

```c#
private static void Main()
{
    using var context = new Context();

    context.Database.EnsureDeleted();
    context.Database.EnsureCreated();

    var groups = context.IceCreams
        .GroupBy(i => i.Popularity)
        .Select(g => new { Popularity = g.Key, Count = g.Count() })
        .OrderByDescending(e => e.Popularity)
        .ToList();

    Debug.Assert(groups.Count == 3);
    Debug.Assert(groups[0].Count == 2);
}
```

The result is different from the first implementation however.
If you really need the individual objects in an `IGrouping<>`, you have to use client evaluation to accomplish this (which is the same mechanism that was implicitly used by EF Core 2.2):

```c#
private static void Main()
{
    using var context = new Context();

    context.Database.EnsureDeleted();
    context.Database.EnsureCreated();

    var groups = context.IceCreams
        .ToList() // <-- manually trigger client eval
        .GroupBy(i => i.Popularity)
        .OrderByDescending(g => g.Key)
        .ToList();

    Debug.Assert(groups.Count == 3);
    Debug.Assert(groups[0].Count() == 2);
}
```

Of course this will retrieve all the individual objects for your groups.

**Comment by domainmurat** [comment]
Why I can't take one or multiple items of grouped data ? Example;

`private static void Main()
{
    using var context = new Context();

    context.Database.EnsureDeleted();
    context.Database.EnsureCreated();

    var groups = context.IceCreams
        .GroupBy(i => i.Popularity)
        .Select(g => new { Popularity = g.Key, Count = g.Count() , g.FirstOrDefault(), g.Take(2)})
        .OrderByDescending(e => e.Popularity)
        .ToList();

    Debug.Assert(groups.Count == 3);
    Debug.Assert(groups[0].Count == 2);
}`

These 'g.FirstOrDefault() ,g.LastOrDefault(), g.Take(2)' can be added to sql query easily

**Comment by mguinness** [comment]
@domainmurat Can you try that code with another provider like [SQLite](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Sqlite)?  If you get the same result, then you should consider asking this question on [Stack Overflow](https://stackoverflow.com/) or raising the issue at [EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore).

**Comment by lauxjpn** [comment]
@domainmurat EF Core currently supports the following `GROUP BY` aggregates (see the [official docs](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#groupby) for further information):

>The aggregate operators EF Core supports are as follows
>
>Average
>Count
>LongCount
>Max
>Min
>Sum

Now, regarding your example query, the `Popularity = g.Key` and `Count = g.Count()` aggregations will work.

It is unclear to me, what you want to accomplish with the rest of the aggregations, because with `g.FirstOrDefault()` you try to squeeze a whole row into a field of a column and with `g.Take(2)` you try to do the same even for the first two rows.

This would not work in SQL either, so please post us the SQL you want to be generated, so we know what you try to accomplish.

We might be able to post you the necessary query in return to achieve what you want.
