### ISSUE TITLE
DbSet query with DateTime.Now parse CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by 491134648** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#964]
### Steps to reproduce
Dbset query with DateTime.Now property with the definition of a DateTime.Now variable, generating sql is not the same, whether there are related configuration items can close the transfer related database function

### The issue
Dbset query with DateTime.Now property with the definition of a DateTime.Now variable, generating sql is not the same, whether there are related configuration items can close the transfer related database function

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
DateTime dateTime = DateTime.Now;
            ActivityCourse activityCourse = _activityCourse.Query(d => d.CourseID == courseID
            && d.StartTime <= dateTime
            && d.EndTime > dateTime
            && d.IsDel == false
            ).FirstOrDefault();
            var data= activityCourse = _activityCourse.Query(d => d.CourseID == courseID
             && d.StartTime <= DateTime.Now
             && d.EndTime > DateTime.Now
             && d.IsDel == false
            ).FirstOrDefault();
```

### Further technical details

MySQL version: 8.0
Operating system: docker img
Pomelo.EntityFrameworkCore.MySql version:2.2.0
Microsoft.AspNetCore.App version: 2.2

Other details about my project setup:
![image](https://user-images.githubusercontent.com/9816794/69477239-bf544480-0e1e-11ea-9928-cc0e00978740.png)

**Comment by mguinness** [comment]
This is not done by the provider but the underlying EF Core library, see discussion at https://github.com/aspnet/EntityFrameworkCore/issues/12338 for more information.

**Comment by lauxjpn** [comment]
This is expected behavior, because if you provide `DateTime.Now` as an **expression**, we will translate it together (as a call to `CURRENT_TIMESTAMP()`) with the rest of the expression to SQL.

However if you first retrieve the result of `DateTime.Now` in your code and save its value to a **variable** (outside of expressions) and then use that variable in an expression when querying the database, the variable will we translated to a parameter of the database command with its value being the value of the variable (containing the time your already retrieved by you previously executed code).

Depending of what behavior you need in your code, you can choose to use either one or the other. But the fact that they are implemented in different ways is intentional.
