### ISSUE TITLE
EF 6.3 support

### ISSUE THREAD

**Issue by IonRobu** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#977]
As EF team ported the EF 6.x to .NetStandard 2.1 to be compatible with .NetCore3.0 - releasing EF 6.3, it would be great if Pomelo MySql adapter can be integrated with EF 6.3.
I'm going to replace EF Core 3.0 with EF 6.3 because EF Core does not support TPT inheritance pattern (and it is not sure if will support this in the future), which is a huge inconvenient for large and complex data domain implementations.

**Comment by lauxjpn** [comment]
Pomelo is not going to ship a provider for EF 6.x, which uses a completely different architecture than EF Core.

EF 6.3 will exists forever, but there will be no improvements made to it anymore (it's forever in maintenance mode now), so you could also say, that it's technically dead.

All the work that had been done for EF in the recent past was to ensure, that customers don't need to upgrade their code to EF Core for legacy applications, but could still leverage .NET Core functionality, and to make the switch to EF Core for applications that *do* need to evolve as smooth as possible.

All future development will happen in EF Core, so that is where we will concentrate our efforts as well.

Pomelo will release a .NET Standard 2.0 compatible version for EF Core 3.1 though (of which I have a pre-release already ready to ship), in case you want to use EF Core in conjunction with .NET Framework.

> I'm going to replace EF Core 3.0 with EF 6.3 because EF Core does not support TPT inheritance pattern (and it is not sure if will support this in the future)

That is like buying a 2004 Nolkia phone instead of a smartphone back in 2012, because the Nokia phone has a better battery life. There might be scenarios where this could be convenient right now, but you need to realize that your are missing out on a lot of already implemented exclusive features and all enhancements made in the future.

It is very likely, that TPT will make the cut for .NET 5, because this is one of the (or maybe *the*) most requested features. See https://github.com/aspnet/EntityFrameworkCore/issues/2266

**Comment by IonRobu** [comment]
You are right, theoretically (and, in almost cases, practically also). However, there are situations, like very big/complex data domains, when is truly difficult without TPT pattern, especially when some DBA are involved in that project.
Anyway, I replaced somehow the pattern with owned entities, and I will stay in my corner, quiet, until the EF team will bring some good news on the subject :)
Thanks for your answer!

**Comment by lauxjpn** [comment]
No problem. BTW, I know that the EF Core team **is** making TPT part of EF Core 5. But this is still a year away.
