### ISSUE TITLE
3.0.1 compatibility with .net framework

### ISSUE THREAD

**Issue by nnikos123** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#985]
Hello , we tried to upgrade a winform App (.NET 4.7.2) using  Pomelo.EntityFrameworkCore.MySql v2.2.6 to v3.0.1 and we got the following error.

---

Error	NU1202	Package Pomelo.EntityFrameworkCore.MySql 3.0.1 is not compatible with net472 (.NETFramework,Version=v4.7.2) / win-x86. Package Pomelo.EntityFrameworkCore.MySql 3.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1)

---

we use also Microsoft.EntityFrameworkCore.SqlServer v3.1 without any issues

is there any limitation in pomelo mysql 3.0.1 when we use it on winforms targeting .net  because when we use it on winforms targeting dotnetcore v3.0.1 is working fine.

**Comment by lauxjpn** [comment]
As you wrote, Pomelo `3.0.1` targets .NET Standard 2.1. This is simply because Pomelo `3.0.1` is compatible with EF Core `3.0.1`, which also targets .NET Standard 2.1.

For EF Core `3.1.0` the design team made the decision to downgrade the targeted .NET Standard to 2.0. Pomelo `3.1.0` is therefore going to target .NET Standard 2.0 as well.

A Pomelo `3.1.0` prerelease is scheduled to be available on NuGet within the next 24 hours.

**Comment by lauxjpn** [comment]
Prerelease [3.1.0-rc1](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/3.1.0-rc1.final) is now available via [NuGet](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.1.0-rc1.final).
It is compatible with .NET Standard 2.0 (and therefore also .NET Framework 4.6.1+).
